/**
 * extern_refresh_config.c
 */

#include "sdkconfig.h"

#ifdef CONFIG_EXTERN_REFRESH_CONFIG

#include <stdint.h>

extern const char *URL_DATA_FILE_TYPE = DEF_URL_DATA_FILE_TYPE;

extern const char *URL_DATA_CURRENT_NORTH = DEF_URL_DATA_CURRENT_NORTH;
extern const char *URL_DATA_CURRENT_SOUTH = DEF_URL_DATA_CURRENT_SOUTH;
extern const char *URL_DATA_TYPICAL_NORTH = DEF_URL_DATA_TYPICAL_NORTH;
extern const char *URL_DATA_TYPICAL_SOUTH = DEF_URL_DATA_TYPICAL_SOUTH;

extern esp_http_client_method_t API_METHOD = DEF_API_METHOD;
extern esp_http_client_auth_type_t API_AUTH_TYPE = DEF_API_AUTH_TYPE;

extern uint32_t API_RETRY_CONN_NUM = DEF_API_RETRY_CONN_NUM;

extern uint32_t MATRIX_RETRY_NUM = DEF_MATRIX_RETRY_NUM;

extern uint8_t DEFAULT_SCALE = DEF_DEFAULT_SCALE;

#ifdef CONFIG_SUPPORT_STROBING
extern uint8_t STROBE_LOW_SCALE = DEF_STROBE_LOW_SCALE;
extern uint8_t STROBE_STEP_HIGH = DEF_STROBE_STEP_HIGH;
extern uint8_t STROBE_STEP_LOW = DEF_STROBE_STEP_LOW;
#endif /* CONFIG_SUPPORT_STROBING */

void macroResetRefreshConfig(void)
{
    URL_DATA_FILE_TYPE = DEF_URL_DATA_FILE_TYPE;

    URL_DATA_CURRENT_NORTH = DEF_URL_DATA_CURRENT_NORTH;
    URL_DATA_CURRENT_SOUTH = DEF_URL_DATA_CURRENT_SOUTH;
    URL_DATA_TYPICAL_NORTH = DEF_URL_DATA_TYPICAL_NORTH;
    URL_DATA_TYPICAL_SOUTH = DEF_URL_DATA_TYPICAL_SOUTH;
    
    API_METHOD = DEF_API_METHOD;
    API_AUTH_TYPE = DEF_API_AUTH_TYPE;
    
    API_RETRY_CONN_NUM = DEF_API_RETRY_CONN_NUM;
    
    MATRIX_RETRY_NUM = DEF_MATRIX_RETRY_NUM;
    
    DEFAULT_SCALE = DEF_DEFAULT_SCALE;
    
#ifdef CONFIG_SUPPORT_STROBING
    STROBE_LOW_SCALE = DEF_STROBE_LOW_SCALE;
    STROBE_STEP_HIGH = DEF_STROBE_STEP_HIGH;
    STROBE_STEP_LOW = DEF_STROBE_STEP_LOW;
#endif /* CONFIG_SUPPORT_STROBING */ 
}

#else /* CONFIG_EXTERN_REFRESH_CONFIG */
#error "extern_refresh_config.c compiled without CONFIG_EXTERN_REFRESH_CONFIG!"
#endif