/**
 * extern_indicators_config.c
 * 
 * Contains indicators_config.h extern variable definitions when
 * CONFIG_EXTERN_INDICATORS_CONFIG is set.
 */

#include "sdkconfig.h"

#ifdef CONFIG_EXTERN_INDICATORS_CONFIG

#include "indicators_config.h"

#include <stdint.h>

uint8_t WHITE_RED_COMPONENT = DEF_WHITE_RED_COMPONENT;
uint8_t WHITE_GREEN_COMPONENT = DEF_WHITE_GREEN_COMPONENT;
uint8_t WHITE_BLUE_COMPONENT = DEF_WHITE_BLUE_COMPONENT;

uint8_t V2_0_OTA_AVAILABLE_RED_COMPONENT = DEF_V2_0_OTA_AVAILABLE_RED_COMPONENT;
uint8_t V2_0_OTA_AVAILABLE_GREEN_COMPONENT = DEF_V2_0_OTA_AVAILABLE_GREEN_COMPONENT;
uint8_t V2_0_OTA_AVAILABLE_BLUE_COMPONENT = DEF_V2_0_OTA_AVAILABLE_BLUE_COMPONENT;

uint8_t V2_0_OTA_FAILURE_RED_COMPONENT = DEF_V2_0_OTA_FAILURE_RED_COMPONENT;
uint8_t V2_0_OTA_FAILURE_GREEN_COMPONENT = DEF_V2_0_OTA_FAILURE_GREEN_COMPONENT;
uint8_t V2_0_OTA_FAILURE_BLUE_COMPONENT = DEF_V2_0_OTA_FAILURE_BLUE_COMPONENT;

uint8_t V2_0_OTA_SUCCESS_RED_COMPONENT = DEF_V2_0_OTA_SUCCESS_RED_COMPONENT;
uint8_t V2_0_OTA_SUCCESS_GREEN_COMPONENT = DEF_V2_0_OTA_SUCCESS_GREEN_COMPONENT;
uint8_t V2_0_OTA_SUCCESS_BLUE_COMPONENT = DEF_V2_0_OTA_SUCCESS_BLUE_COMPONENT;

uint8_t V2_0_WIFI_CONNECTED_COLOR_RED = DEF_V2_0_WIFI_CONNECTED_COLOR_RED;
uint8_t V2_0_WIFI_CONNECTED_COLOR_GREEN = DEF_V2_0_WIFI_CONNECTED_COLOR_GREEN;
uint8_t V2_0_WIFI_CONNECTED_COLOR_BLUE = DEF_V2_0_WIFI_CONNECTED_COLOR_BLUE;

uint8_t V2_0_OTA_UPDATE_COLOR_RED = DEF_V2_0_OTA_UPDATE_COLOR_RED;
uint8_t V2_0_OTA_UPDATE_COLOR_GREEN = DEF_V2_0_OTA_UPDATE_COLOR_GREEN;
uint8_t V2_0_OTA_UPDATE_COLOR_BLUE = DEF_V2_0_OTA_UPDATE_COLOR_BLUE;

uint8_t V2_0_NORTHBOUND_COLOR_RED = DEF_V2_0_NORTHBOUND_COLOR_RED;
uint8_t V2_0_NORTHBOUND_COLOR_GREEN = DEF_V2_0_NORTHBOUND_COLOR_GREEN;
uint8_t V2_0_NORTHBOUND_COLOR_BLUE = DEF_V2_0_NORTHBOUND_COLOR_BLUE;

uint8_t V2_0_SOUTHBOUND_COLOR_RED = DEF_V2_0_SOUTHBOUND_COLOR_RED;
uint8_t V2_0_SOUTHBOUND_COLOR_GREEN = DEF_V2_0_SOUTHBOUND_COLOR_GREEN;
uint8_t V2_0_SOUTHBOUND_COLOR_BLUE = DEF_V2_0_SOUTHBOUND_COLOR_BLUE;

void macroResetIndicatorsConfig(void)
{
    WHITE_RED_COMPONENT = DEF_WHITE_RED_COMPONENT;
    WHITE_GREEN_COMPONENT = DEF_WHITE_GREEN_COMPONENT;
    WHITE_BLUE_COMPONENT = DEF_WHITE_BLUE_COMPONENT;

    V2_0_OTA_AVAILABLE_RED_COMPONENT = DEF_V2_0_OTA_AVAILABLE_RED_COMPONENT;
    V2_0_OTA_AVAILABLE_GREEN_COMPONENT = DEF_V2_0_OTA_AVAILABLE_GREEN_COMPONENT;
    V2_0_OTA_AVAILABLE_BLUE_COMPONENT = DEF_V2_0_OTA_AVAILABLE_BLUE_COMPONENT;

    V2_0_OTA_FAILURE_RED_COMPONENT = DEF_V2_0_OTA_FAILURE_RED_COMPONENT;
    V2_0_OTA_FAILURE_GREEN_COMPONENT = DEF_V2_0_OTA_FAILURE_GREEN_COMPONENT;
    V2_0_OTA_FAILURE_BLUE_COMPONENT = DEF_V2_0_OTA_FAILURE_BLUE_COMPONENT;

    V2_0_OTA_SUCCESS_RED_COMPONENT = DEF_V2_0_OTA_SUCCESS_RED_COMPONENT;
    V2_0_OTA_SUCCESS_GREEN_COMPONENT = DEF_V2_0_OTA_SUCCESS_GREEN_COMPONENT;
    V2_0_OTA_SUCCESS_BLUE_COMPONENT = DEF_V2_0_OTA_SUCCESS_BLUE_COMPONENT;

    V2_0_WIFI_CONNECTED_COLOR_RED = DEF_V2_0_WIFI_CONNECTED_COLOR_RED;
    V2_0_WIFI_CONNECTED_COLOR_GREEN = DEF_V2_0_WIFI_CONNECTED_COLOR_GREEN;
    V2_0_WIFI_CONNECTED_COLOR_BLUE = DEF_V2_0_WIFI_CONNECTED_COLOR_BLUE;

    V2_0_OTA_UPDATE_COLOR_RED = DEF_V2_0_OTA_UPDATE_COLOR_RED;
    V2_0_OTA_UPDATE_COLOR_GREEN = DEF_V2_0_OTA_UPDATE_COLOR_GREEN;
    V2_0_OTA_UPDATE_COLOR_BLUE = DEF_V2_0_OTA_UPDATE_COLOR_BLUE;

    V2_0_NORTHBOUND_COLOR_RED = DEF_V2_0_NORTHBOUND_COLOR_RED;
    V2_0_NORTHBOUND_COLOR_GREEN = DEF_V2_0_NORTHBOUND_COLOR_GREEN;
    V2_0_NORTHBOUND_COLOR_BLUE = DEF_V2_0_NORTHBOUND_COLOR_BLUE;
    
    V2_0_SOUTHBOUND_COLOR_RED = DEF_V2_0_SOUTHBOUND_COLOR_RED;
    V2_0_SOUTHBOUND_COLOR_GREEN = DEF_V2_0_SOUTHBOUND_COLOR_GREEN;
    V2_0_SOUTHBOUND_COLOR_BLUE = DEF_V2_0_SOUTHBOUND_COLOR_BLUE;
}

#else
#error "extern_indicators_config.c compiled without CONFIG_EXTERN_INDICATORS_CONFIG!"
#endif /* CONFIG_EXTERN_INDICATORS_CONFIG */