/**
 * indicators_config.h
 * 
 * Contains macro configuration options for indicators.c, with the option to
 * use extern variables instead of macros by defining CONFIG_EXTERN_INDICATORS_CONFIG.
 * This replacement is useful for testing with different values of configuration
 * macros while maintaining the benefits of static configuration options.
 */

#include "sdkconfig.h"

/**
 * Default definitions of macros, which add a layer of indirection allowing
 * extern macro replacements to be set to the value that the macro would be.
 */

#define DEF_WHITE_RED_COMPONENT (32)
#define DEF_WHITE_GREEN_COMPONENT (48)
#define DEF_WHITE_BLUE_COMPONENT (32)

#define DEF_V2_0_OTA_AVAILABLE_RED_COMPONENT (0)
#define DEF_V2_0_OTA_AVAILABLE_GREEN_COMPONENT (255)
#define DEF_V2_0_OTA_AVAILABLE_BLUE_COMPONENT (0)

#define DEF_V2_0_OTA_FAILURE_RED_COMPONENT (255)
#define DEF_V2_0_OTA_FAILURE_GREEN_COMPONENT (0)
#define DEF_V2_0_OTA_FAILURE_BLUE_COMPONENT (0)

#define DEF_V2_0_OTA_SUCCESS_RED_COMPONENT (0)
#define DEF_V2_0_OTA_SUCCESS_GREEN_COMPONENT (255)
#define DEF_V2_0_OTA_SUCCESS_BLUE_COMPONENT (0)

#define DEF_V2_0_WIFI_CONNECTED_COLOR_RED DEF_WHITE_RED_COMPONENT
#define DEF_V2_0_WIFI_CONNECTED_COLOR_GREEN DEF_WHITE_GREEN_COMPONENT
#define DEF_V2_0_WIFI_CONNECTED_COLOR_BLUE DEF_WHITE_BLUE_COMPONENT

#define DEF_V2_0_OTA_UPDATE_COLOR_RED DEF_WHITE_RED_COMPONENT
#define DEF_V2_0_OTA_UPDATE_COLOR_GREEN DEF_WHITE_GREEN_COMPONENT
#define DEF_V2_0_OTA_UPDATE_COLOR_BLUE DEF_WHITE_BLUE_COMPONENT

#define DEF_V2_0_NORTHBOUND_COLOR_RED DEF_WHITE_RED_COMPONENT
#define DEF_V2_0_NORTHBOUND_COLOR_GREEN DEF_WHITE_GREEN_COMPONENT
#define DEF_V2_0_NORTHBOUND_COLOR_BLUE DEF_WHITE_BLUE_COMPONENT

#define DEF_V2_0_SOUTHBOUND_COLOR_RED DEF_WHITE_RED_COMPONENT
#define DEF_V2_0_SOUTHBOUND_COLOR_GREEN DEF_WHITE_GREEN_COMPONENT
#define DEF_V2_0_SOUTHBOUND_COLOR_BLUE DEF_WHITE_BLUE_COMPONENT

#ifndef CONFIG_EXTERN_INDICATORS_CONFIG

/**
 * Macro configuration options, set by the default macros above.
 */

#define WHITE_RED_COMPONENT DEF_WHITE_RED_COMPONENT
#define WHITE_GREEN_COMPONENT DEF_WHITE_GREEN_COMPONENT
#define WHITE_BLUE_COMPONENT DEF_WHITE_BLUE_COMPONENT

#define V2_0_OTA_AVAILABLE_RED_COMPONENT DEF_V2_0_OTA_AVAILABLE_RED_COMPONENT
#define V2_0_OTA_AVAILABLE_GREEN_COMPONENT DEF_V2_0_OTA_AVAILABLE_GREEN_COMPONENT
#define V2_0_OTA_AVAILABLE_BLUE_COMPONENT DEF_V2_0_OTA_AVAILABLE_BLUE_COMPONENT

#define V2_0_OTA_FAILURE_RED_COMPONENT DEF_V2_0_OTA_FAILURE_RED_COMPONENT
#define V2_0_OTA_FAILURE_GREEN_COMPONENT DEF_V2_0_OTA_FAILURE_GREEN_COMPONENT
#define V2_0_OTA_FAILURE_BLUE_COMPONENT DEF_V2_0_OTA_FAILURE_BLUE_COMPONENT

#define V2_0_OTA_SUCCESS_RED_COMPONENT DEF_V2_0_OTA_SUCCESS_RED_COMPONENT
#define V2_0_OTA_SUCCESS_GREEN_COMPONENT DEF_V2_0_OTA_SUCCESS_GREEN_COMPONENT
#define V2_0_OTA_SUCCESS_BLUE_COMPONENT DEF_V2_0_OTA_SUCCESS_BLUE_COMPONENT

#define V2_0_WIFI_CONNECTED_COLOR_RED DEF_V2_0_WIFI_CONNECTED_COLOR_RED
#define V2_0_WIFI_CONNECTED_COLOR_GREEN DEF_V2_0_WIFI_CONNECTED_COLOR_GREEN
#define V2_0_WIFI_CONNECTED_COLOR_BLUE DEF_V2_0_WIFI_CONNECTED_COLOR_BLUE

#define V2_0_OTA_UPDATE_COLOR_RED DEF_V2_0_OTA_UPDATE_COLOR_RED
#define V2_0_OTA_UPDATE_COLOR_GREEN DEF_V2_0_OTA_UPDATE_COLOR_GREEN
#define V2_0_OTA_UPDATE_COLOR_BLUE DEF_V2_0_OTA_UPDATE_COLOR_BLUE

#define V2_0_NORTHBOUND_COLOR_RED DEF_V2_0_NORTHBOUND_COLOR_RED
#define V2_0_NORTHBOUND_COLOR_GREEN DEF_V2_0_NORTHBOUND_COLOR_GREEN
#define V2_0_NORTHBOUND_COLOR_BLUE DEF_V2_0_NORTHBOUND_COLOR_BLUE

#define V2_0_SOUTHBOUND_COLOR_RED DEF_V2_0_SOUTHBOUND_COLOR_RED
#define V2_0_SOUTHBOUND_COLOR_GREEN DEF_V2_0_SOUTHBOUND_COLOR_GREEN
#define V2_0_SOUTHBOUND_COLOR_BLUE DEF_V2_0_SOUTHBOUND_COLOR_BLUE

#else /* CONFIG_EXTERN_INDICATORS_CONFIG */

/**
 * Extern definitions of configuration options, which replace macros to allow
 * testing with multiple values of macros.
 */

#include <stdint.h>

extern uint8_t WHITE_RED_COMPONENT;
extern uint8_t WHITE_GREEN_COMPONENT;
extern uint8_t WHITE_BLUE_COMPONENT;

extern uint8_t V2_0_OTA_AVAILABLE_RED_COMPONENT;
extern uint8_t V2_0_OTA_AVAILABLE_GREEN_COMPONENT;
extern uint8_t V2_0_OTA_AVAILABLE_BLUE_COMPONENT;

extern uint8_t V2_0_OTA_FAILURE_RED_COMPONENT;
extern uint8_t V2_0_OTA_FAILURE_GREEN_COMPONENT;
extern uint8_t V2_0_OTA_FAILURE_BLUE_COMPONENT;

extern uint8_t V2_0_OTA_SUCCESS_RED_COMPONENT;
extern uint8_t V2_0_OTA_SUCCESS_GREEN_COMPONENT;
extern uint8_t V2_0_OTA_SUCCESS_BLUE_COMPONENT;

extern uint8_t V2_0_WIFI_CONNECTED_COLOR_RED;
extern uint8_t V2_0_WIFI_CONNECTED_COLOR_GREEN;
extern uint8_t V2_0_WIFI_CONNECTED_COLOR_BLUE;

extern uint8_t V2_0_OTA_UPDATE_COLOR_RED;
extern uint8_t V2_0_OTA_UPDATE_COLOR_GREEN;
extern uint8_t V2_0_OTA_UPDATE_COLOR_BLUE;

extern uint8_t V2_0_NORTHBOUND_COLOR_RED;youtube

extern uint8_t V2_0_NORTHBOUND_COLOR_GREEN;
extern uint8_t V2_0_NORTHBOUND_COLOR_BLUE;

extern uint8_t V2_0_SOUTHBOUND_COLOR_RED;
extern uint8_t V2_0_SOUTHBOUND_COLOR_GREEN;
extern uint8_t V2_0_SOUTHBOUND_COLOR_BLUE;

void macroResetIndicatorsConfig(void);

#endif /* CONFIG_EXTERN_INDICATORS_CONFIG */