/**
 * extern_ota_config.c
 * 
 * Contains ota_config.h extern variable definitions when 
 * CONFIG_OTA_EXTERN_MACROS is set.
 */


#include "sdkconfig.h"

#ifdef CONFIG_OTA_EXTERN_MACROS

#include "ota_config.h"

#include <stdint.h>

uint32_t RETRY_CONNECT_OTA_AVAILABLE = DEF_RETRY_CONNECT_OTA_AVAILABLE;
uint32_t OTA_RECV_BUF_SIZE = DEF_OTA_RECV_BUF_SIZE;

uint32_t OTA_HARDWARE_VERSION = DEF_OTA_HARDWARE_VERSION;
uint32_t OTA_REVISION_VERSION = DEF_OTA_REVISION_VERSION;
uint32_t OTA_MAJOR_VERSION = DEF_OTA_MAJOR_VERSION;
uint32_t OTA_MINOR_VERSION = DEF_OTA_MINOR_VERSION;
uint32_t OTA_PATCH_VERSION = DEF_OTA_PATCH_VERSION;

const char *HARDWARE_VERSION_KEY = DEF_HARDWARE_VERSION_KEY;
const char *HARDWARE_REVISION_KEY = DEF_HARDWARE_REVISION_KEY;
const char *FIRMWARE_MAJOR_KEY = DEF_FIRMWARE_MAJOR_KEY;
const char *FIRMWARE_MINOR_KEY = DEF_FIRMWARE_MINOR_KEY;
const char *FIRMWARE_PATCH_KEY = DEF_FIRMWARE_PATCH_KEY;

void macroResetOTAConfig(void)
{
    RETRY_CONNECT_OTA_AVAILABLE = DEF_RETRY_CONNECT_OTA_AVAILABLE;
    OTA_RECV_BUF_SIZE = DEF_OTA_RECV_BUF_SIZE;

    OTA_HARDWARE_VERSION = DEF_OTA_HARDWARE_VERSION;
    OTA_REVISION_VERSION = DEF_OTA_REVISION_VERSION;
    OTA_MAJOR_VERSION = DEF_OTA_MAJOR_VERSION;
    OTA_MINOR_VERSION = DEF_OTA_MINOR_VERSION;
    OTA_PATCH_VERSION = DEF_OTA_PATCH_VERSION;

    HARDWARE_VERSION_KEY = DEF_HARDWARE_VERSION_KEY;
    HARDWARE_REVISION_KEY = DEF_HARDWARE_REVISION_KEY;
    FIRMWARE_MAJOR_KEY = DEF_FIRMWARE_MAJOR_KEY;
    FIRMWARE_MINOR_KEY = DEF_FIRMWARE_MINOR_KEY;
    FIRMWARE_PATCH_KEY = DEF_FIRMWARE_PATCH_KEY;
}

#else /* CONFIG_OTA_EXTERN_MACROS */
#error "ota_test.c compiled without CONFIG_OTA_EXTERN_MACRO defined!"
#endif /* CONFIG_OTA_EXTERN_MACROS */
