/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKLED_MATRIX_H
#define _MOCKLED_MATRIX_H

#include "unity.h"
#include "led_matrix.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockled_matrix_Init(void);
void Mockled_matrix_Destroy(void);
void Mockled_matrix_Verify(void);




#define initLedMatrix_Ignore() TEST_FAIL_MESSAGE("initLedMatrix requires _IgnoreAndReturn");
#define initLedMatrix_IgnoreAndReturn(cmock_retval) initLedMatrix_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void initLedMatrix_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define initLedMatrix_StopIgnore() initLedMatrix_CMockStopIgnore()
void initLedMatrix_CMockStopIgnore(void);
#define initLedMatrix_Expect() TEST_FAIL_MESSAGE("initLedMatrix requires _ExpectAndReturn");
#define initLedMatrix_ExpectAndReturn(cmock_retval) initLedMatrix_CMockExpectAndReturn(__LINE__, cmock_retval)
void initLedMatrix_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_initLedMatrix_CALLBACK)(int cmock_num_calls);
void initLedMatrix_AddCallback(CMOCK_initLedMatrix_CALLBACK Callback);
void initLedMatrix_Stub(CMOCK_initLedMatrix_CALLBACK Callback);
#define initLedMatrix_StubWithCallback initLedMatrix_Stub
#define getLedMatrixStatus_Ignore() TEST_FAIL_MESSAGE("getLedMatrixStatus requires _IgnoreAndReturn");
#define getLedMatrixStatus_IgnoreAndReturn(cmock_retval) getLedMatrixStatus_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void getLedMatrixStatus_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define getLedMatrixStatus_StopIgnore() getLedMatrixStatus_CMockStopIgnore()
void getLedMatrixStatus_CMockStopIgnore(void);
#define getLedMatrixStatus_Expect() TEST_FAIL_MESSAGE("getLedMatrixStatus requires _ExpectAndReturn");
#define getLedMatrixStatus_ExpectAndReturn(cmock_retval) getLedMatrixStatus_CMockExpectAndReturn(__LINE__, cmock_retval)
void getLedMatrixStatus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_getLedMatrixStatus_CALLBACK)(int cmock_num_calls);
void getLedMatrixStatus_AddCallback(CMOCK_getLedMatrixStatus_CALLBACK Callback);
void getLedMatrixStatus_Stub(CMOCK_getLedMatrixStatus_CALLBACK Callback);
#define getLedMatrixStatus_StubWithCallback getLedMatrixStatus_Stub
#define matSetOperatingMode_Ignore() TEST_FAIL_MESSAGE("matSetOperatingMode requires _IgnoreAndReturn");
#define matSetOperatingMode_IgnoreAndReturn(cmock_retval) matSetOperatingMode_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetOperatingMode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetOperatingMode_StopIgnore() matSetOperatingMode_CMockStopIgnore()
void matSetOperatingMode_CMockStopIgnore(void);
#define matSetOperatingMode_Expect(setting) TEST_FAIL_MESSAGE("matSetOperatingMode requires _ExpectAndReturn");
#define matSetOperatingMode_ExpectAndReturn(setting, cmock_retval) matSetOperatingMode_CMockExpectAndReturn(__LINE__, setting, cmock_retval)
void matSetOperatingMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, enum Operation setting, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetOperatingMode_CALLBACK)(enum Operation setting, int cmock_num_calls);
void matSetOperatingMode_AddCallback(CMOCK_matSetOperatingMode_CALLBACK Callback);
void matSetOperatingMode_Stub(CMOCK_matSetOperatingMode_CALLBACK Callback);
#define matSetOperatingMode_StubWithCallback matSetOperatingMode_Stub
#define matSetOperatingMode_IgnoreArg_setting() matSetOperatingMode_CMockIgnoreArg_setting(__LINE__)
void matSetOperatingMode_CMockIgnoreArg_setting(UNITY_LINE_TYPE cmock_line);
#define matSetOpenShortDetection_Ignore() TEST_FAIL_MESSAGE("matSetOpenShortDetection requires _IgnoreAndReturn");
#define matSetOpenShortDetection_IgnoreAndReturn(cmock_retval) matSetOpenShortDetection_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetOpenShortDetection_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetOpenShortDetection_StopIgnore() matSetOpenShortDetection_CMockStopIgnore()
void matSetOpenShortDetection_CMockStopIgnore(void);
#define matSetOpenShortDetection_Expect(setting) TEST_FAIL_MESSAGE("matSetOpenShortDetection requires _ExpectAndReturn");
#define matSetOpenShortDetection_ExpectAndReturn(setting, cmock_retval) matSetOpenShortDetection_CMockExpectAndReturn(__LINE__, setting, cmock_retval)
void matSetOpenShortDetection_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, enum ShortDetectionEnable setting, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetOpenShortDetection_CALLBACK)(enum ShortDetectionEnable setting, int cmock_num_calls);
void matSetOpenShortDetection_AddCallback(CMOCK_matSetOpenShortDetection_CALLBACK Callback);
void matSetOpenShortDetection_Stub(CMOCK_matSetOpenShortDetection_CALLBACK Callback);
#define matSetOpenShortDetection_StubWithCallback matSetOpenShortDetection_Stub
#define matSetOpenShortDetection_IgnoreArg_setting() matSetOpenShortDetection_CMockIgnoreArg_setting(__LINE__)
void matSetOpenShortDetection_CMockIgnoreArg_setting(UNITY_LINE_TYPE cmock_line);
#define matSetLogicLevel_Ignore() TEST_FAIL_MESSAGE("matSetLogicLevel requires _IgnoreAndReturn");
#define matSetLogicLevel_IgnoreAndReturn(cmock_retval) matSetLogicLevel_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetLogicLevel_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetLogicLevel_StopIgnore() matSetLogicLevel_CMockStopIgnore()
void matSetLogicLevel_CMockStopIgnore(void);
#define matSetLogicLevel_Expect(setting) TEST_FAIL_MESSAGE("matSetLogicLevel requires _ExpectAndReturn");
#define matSetLogicLevel_ExpectAndReturn(setting, cmock_retval) matSetLogicLevel_CMockExpectAndReturn(__LINE__, setting, cmock_retval)
void matSetLogicLevel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, enum LogicLevel setting, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetLogicLevel_CALLBACK)(enum LogicLevel setting, int cmock_num_calls);
void matSetLogicLevel_AddCallback(CMOCK_matSetLogicLevel_CALLBACK Callback);
void matSetLogicLevel_Stub(CMOCK_matSetLogicLevel_CALLBACK Callback);
#define matSetLogicLevel_StubWithCallback matSetLogicLevel_Stub
#define matSetLogicLevel_IgnoreArg_setting() matSetLogicLevel_CMockIgnoreArg_setting(__LINE__)
void matSetLogicLevel_CMockIgnoreArg_setting(UNITY_LINE_TYPE cmock_line);
#define matSetSWxSetting_Ignore() TEST_FAIL_MESSAGE("matSetSWxSetting requires _IgnoreAndReturn");
#define matSetSWxSetting_IgnoreAndReturn(cmock_retval) matSetSWxSetting_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetSWxSetting_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetSWxSetting_StopIgnore() matSetSWxSetting_CMockStopIgnore()
void matSetSWxSetting_CMockStopIgnore(void);
#define matSetSWxSetting_Expect(setting) TEST_FAIL_MESSAGE("matSetSWxSetting requires _ExpectAndReturn");
#define matSetSWxSetting_ExpectAndReturn(setting, cmock_retval) matSetSWxSetting_CMockExpectAndReturn(__LINE__, setting, cmock_retval)
void matSetSWxSetting_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, enum SWXSetting setting, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetSWxSetting_CALLBACK)(enum SWXSetting setting, int cmock_num_calls);
void matSetSWxSetting_AddCallback(CMOCK_matSetSWxSetting_CALLBACK Callback);
void matSetSWxSetting_Stub(CMOCK_matSetSWxSetting_CALLBACK Callback);
#define matSetSWxSetting_StubWithCallback matSetSWxSetting_Stub
#define matSetSWxSetting_IgnoreArg_setting() matSetSWxSetting_CMockIgnoreArg_setting(__LINE__)
void matSetSWxSetting_CMockIgnoreArg_setting(UNITY_LINE_TYPE cmock_line);
#define matSetGlobalCurrentControl_Ignore() TEST_FAIL_MESSAGE("matSetGlobalCurrentControl requires _IgnoreAndReturn");
#define matSetGlobalCurrentControl_IgnoreAndReturn(cmock_retval) matSetGlobalCurrentControl_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetGlobalCurrentControl_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetGlobalCurrentControl_StopIgnore() matSetGlobalCurrentControl_CMockStopIgnore()
void matSetGlobalCurrentControl_CMockStopIgnore(void);
#define matSetGlobalCurrentControl_Expect(value) TEST_FAIL_MESSAGE("matSetGlobalCurrentControl requires _ExpectAndReturn");
#define matSetGlobalCurrentControl_ExpectAndReturn(value, cmock_retval) matSetGlobalCurrentControl_CMockExpectAndReturn(__LINE__, value, cmock_retval)
void matSetGlobalCurrentControl_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t value, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetGlobalCurrentControl_CALLBACK)(uint8_t value, int cmock_num_calls);
void matSetGlobalCurrentControl_AddCallback(CMOCK_matSetGlobalCurrentControl_CALLBACK Callback);
void matSetGlobalCurrentControl_Stub(CMOCK_matSetGlobalCurrentControl_CALLBACK Callback);
#define matSetGlobalCurrentControl_StubWithCallback matSetGlobalCurrentControl_Stub
#define matSetGlobalCurrentControl_IgnoreArg_value() matSetGlobalCurrentControl_CMockIgnoreArg_value(__LINE__)
void matSetGlobalCurrentControl_CMockIgnoreArg_value(UNITY_LINE_TYPE cmock_line);
#define matSetResistorPullupSetting_Ignore() TEST_FAIL_MESSAGE("matSetResistorPullupSetting requires _IgnoreAndReturn");
#define matSetResistorPullupSetting_IgnoreAndReturn(cmock_retval) matSetResistorPullupSetting_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetResistorPullupSetting_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetResistorPullupSetting_StopIgnore() matSetResistorPullupSetting_CMockStopIgnore()
void matSetResistorPullupSetting_CMockStopIgnore(void);
#define matSetResistorPullupSetting_Expect(setting) TEST_FAIL_MESSAGE("matSetResistorPullupSetting requires _ExpectAndReturn");
#define matSetResistorPullupSetting_ExpectAndReturn(setting, cmock_retval) matSetResistorPullupSetting_CMockExpectAndReturn(__LINE__, setting, cmock_retval)
void matSetResistorPullupSetting_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, enum ResistorSetting setting, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetResistorPullupSetting_CALLBACK)(enum ResistorSetting setting, int cmock_num_calls);
void matSetResistorPullupSetting_AddCallback(CMOCK_matSetResistorPullupSetting_CALLBACK Callback);
void matSetResistorPullupSetting_Stub(CMOCK_matSetResistorPullupSetting_CALLBACK Callback);
#define matSetResistorPullupSetting_StubWithCallback matSetResistorPullupSetting_Stub
#define matSetResistorPullupSetting_IgnoreArg_setting() matSetResistorPullupSetting_CMockIgnoreArg_setting(__LINE__)
void matSetResistorPullupSetting_CMockIgnoreArg_setting(UNITY_LINE_TYPE cmock_line);
#define matSetResistorPulldownSetting_Ignore() TEST_FAIL_MESSAGE("matSetResistorPulldownSetting requires _IgnoreAndReturn");
#define matSetResistorPulldownSetting_IgnoreAndReturn(cmock_retval) matSetResistorPulldownSetting_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetResistorPulldownSetting_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetResistorPulldownSetting_StopIgnore() matSetResistorPulldownSetting_CMockStopIgnore()
void matSetResistorPulldownSetting_CMockStopIgnore(void);
#define matSetResistorPulldownSetting_Expect(setting) TEST_FAIL_MESSAGE("matSetResistorPulldownSetting requires _ExpectAndReturn");
#define matSetResistorPulldownSetting_ExpectAndReturn(setting, cmock_retval) matSetResistorPulldownSetting_CMockExpectAndReturn(__LINE__, setting, cmock_retval)
void matSetResistorPulldownSetting_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, enum ResistorSetting setting, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetResistorPulldownSetting_CALLBACK)(enum ResistorSetting setting, int cmock_num_calls);
void matSetResistorPulldownSetting_AddCallback(CMOCK_matSetResistorPulldownSetting_CALLBACK Callback);
void matSetResistorPulldownSetting_Stub(CMOCK_matSetResistorPulldownSetting_CALLBACK Callback);
#define matSetResistorPulldownSetting_StubWithCallback matSetResistorPulldownSetting_Stub
#define matSetResistorPulldownSetting_IgnoreArg_setting() matSetResistorPulldownSetting_CMockIgnoreArg_setting(__LINE__)
void matSetResistorPulldownSetting_CMockIgnoreArg_setting(UNITY_LINE_TYPE cmock_line);
#define matSetPWMFrequency_Ignore() TEST_FAIL_MESSAGE("matSetPWMFrequency requires _IgnoreAndReturn");
#define matSetPWMFrequency_IgnoreAndReturn(cmock_retval) matSetPWMFrequency_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetPWMFrequency_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetPWMFrequency_StopIgnore() matSetPWMFrequency_CMockStopIgnore()
void matSetPWMFrequency_CMockStopIgnore(void);
#define matSetPWMFrequency_Expect(freq) TEST_FAIL_MESSAGE("matSetPWMFrequency requires _ExpectAndReturn");
#define matSetPWMFrequency_ExpectAndReturn(freq, cmock_retval) matSetPWMFrequency_CMockExpectAndReturn(__LINE__, freq, cmock_retval)
void matSetPWMFrequency_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, enum PWMFrequency freq, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetPWMFrequency_CALLBACK)(enum PWMFrequency freq, int cmock_num_calls);
void matSetPWMFrequency_AddCallback(CMOCK_matSetPWMFrequency_CALLBACK Callback);
void matSetPWMFrequency_Stub(CMOCK_matSetPWMFrequency_CALLBACK Callback);
#define matSetPWMFrequency_StubWithCallback matSetPWMFrequency_Stub
#define matSetPWMFrequency_IgnoreArg_freq() matSetPWMFrequency_CMockIgnoreArg_freq(__LINE__)
void matSetPWMFrequency_CMockIgnoreArg_freq(UNITY_LINE_TYPE cmock_line);
#define matReset_Ignore() TEST_FAIL_MESSAGE("matReset requires _IgnoreAndReturn");
#define matReset_IgnoreAndReturn(cmock_retval) matReset_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matReset_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matReset_StopIgnore() matReset_CMockStopIgnore()
void matReset_CMockStopIgnore(void);
#define matReset_Expect() TEST_FAIL_MESSAGE("matReset requires _ExpectAndReturn");
#define matReset_ExpectAndReturn(cmock_retval) matReset_CMockExpectAndReturn(__LINE__, cmock_retval)
void matReset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matReset_CALLBACK)(int cmock_num_calls);
void matReset_AddCallback(CMOCK_matReset_CALLBACK Callback);
void matReset_Stub(CMOCK_matReset_CALLBACK Callback);
#define matReset_StubWithCallback matReset_Stub
#define matSetColor_Ignore() TEST_FAIL_MESSAGE("matSetColor requires _IgnoreAndReturn");
#define matSetColor_IgnoreAndReturn(cmock_retval) matSetColor_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetColor_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetColor_StopIgnore() matSetColor_CMockStopIgnore()
void matSetColor_CMockStopIgnore(void);
#define matSetColor_Expect(ledNum, red, green, blue) TEST_FAIL_MESSAGE("matSetColor requires _ExpectAndReturn");
#define matSetColor_ExpectAndReturn(ledNum, red, green, blue, cmock_retval) matSetColor_CMockExpectAndReturn(__LINE__, ledNum, red, green, blue, cmock_retval)
void matSetColor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t ledNum, uint8_t red, uint8_t green, uint8_t blue, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetColor_CALLBACK)(uint16_t ledNum, uint8_t red, uint8_t green, uint8_t blue, int cmock_num_calls);
void matSetColor_AddCallback(CMOCK_matSetColor_CALLBACK Callback);
void matSetColor_Stub(CMOCK_matSetColor_CALLBACK Callback);
#define matSetColor_StubWithCallback matSetColor_Stub
#define matSetColor_IgnoreArg_ledNum() matSetColor_CMockIgnoreArg_ledNum(__LINE__)
void matSetColor_CMockIgnoreArg_ledNum(UNITY_LINE_TYPE cmock_line);
#define matSetColor_IgnoreArg_red() matSetColor_CMockIgnoreArg_red(__LINE__)
void matSetColor_CMockIgnoreArg_red(UNITY_LINE_TYPE cmock_line);
#define matSetColor_IgnoreArg_green() matSetColor_CMockIgnoreArg_green(__LINE__)
void matSetColor_CMockIgnoreArg_green(UNITY_LINE_TYPE cmock_line);
#define matSetColor_IgnoreArg_blue() matSetColor_CMockIgnoreArg_blue(__LINE__)
void matSetColor_CMockIgnoreArg_blue(UNITY_LINE_TYPE cmock_line);
#define matSetScaling_Ignore() TEST_FAIL_MESSAGE("matSetScaling requires _IgnoreAndReturn");
#define matSetScaling_IgnoreAndReturn(cmock_retval) matSetScaling_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetScaling_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetScaling_StopIgnore() matSetScaling_CMockStopIgnore()
void matSetScaling_CMockStopIgnore(void);
#define matSetScaling_Expect(ledNum, red, green, blue) TEST_FAIL_MESSAGE("matSetScaling requires _ExpectAndReturn");
#define matSetScaling_ExpectAndReturn(ledNum, red, green, blue, cmock_retval) matSetScaling_CMockExpectAndReturn(__LINE__, ledNum, red, green, blue, cmock_retval)
void matSetScaling_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t ledNum, uint8_t red, uint8_t green, uint8_t blue, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetScaling_CALLBACK)(uint16_t ledNum, uint8_t red, uint8_t green, uint8_t blue, int cmock_num_calls);
void matSetScaling_AddCallback(CMOCK_matSetScaling_CALLBACK Callback);
void matSetScaling_Stub(CMOCK_matSetScaling_CALLBACK Callback);
#define matSetScaling_StubWithCallback matSetScaling_Stub
#define matSetScaling_IgnoreArg_ledNum() matSetScaling_CMockIgnoreArg_ledNum(__LINE__)
void matSetScaling_CMockIgnoreArg_ledNum(UNITY_LINE_TYPE cmock_line);
#define matSetScaling_IgnoreArg_red() matSetScaling_CMockIgnoreArg_red(__LINE__)
void matSetScaling_CMockIgnoreArg_red(UNITY_LINE_TYPE cmock_line);
#define matSetScaling_IgnoreArg_green() matSetScaling_CMockIgnoreArg_green(__LINE__)
void matSetScaling_CMockIgnoreArg_green(UNITY_LINE_TYPE cmock_line);
#define matSetScaling_IgnoreArg_blue() matSetScaling_CMockIgnoreArg_blue(__LINE__)
void matSetScaling_CMockIgnoreArg_blue(UNITY_LINE_TYPE cmock_line);
#define matInitialize_Ignore() TEST_FAIL_MESSAGE("matInitialize requires _IgnoreAndReturn");
#define matInitialize_IgnoreAndReturn(cmock_retval) matInitialize_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matInitialize_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matInitialize_StopIgnore() matInitialize_CMockStopIgnore()
void matInitialize_CMockStopIgnore(void);
#define matInitialize_Expect(port, sdaPin, sclPin) TEST_FAIL_MESSAGE("matInitialize requires _ExpectAndReturn");
#define matInitialize_ExpectAndReturn(port, sdaPin, sclPin, cmock_retval) matInitialize_CMockExpectAndReturn(__LINE__, port, sdaPin, sclPin, cmock_retval)
void matInitialize_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, i2c_port_num_t port, gpio_num_t sdaPin, gpio_num_t sclPin, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matInitialize_CALLBACK)(i2c_port_num_t port, gpio_num_t sdaPin, gpio_num_t sclPin, int cmock_num_calls);
void matInitialize_AddCallback(CMOCK_matInitialize_CALLBACK Callback);
void matInitialize_Stub(CMOCK_matInitialize_CALLBACK Callback);
#define matInitialize_StubWithCallback matInitialize_Stub
#define matInitialize_IgnoreArg_port() matInitialize_CMockIgnoreArg_port(__LINE__)
void matInitialize_CMockIgnoreArg_port(UNITY_LINE_TYPE cmock_line);
#define matInitialize_IgnoreArg_sdaPin() matInitialize_CMockIgnoreArg_sdaPin(__LINE__)
void matInitialize_CMockIgnoreArg_sdaPin(UNITY_LINE_TYPE cmock_line);
#define matInitialize_IgnoreArg_sclPin() matInitialize_CMockIgnoreArg_sclPin(__LINE__)
void matInitialize_CMockIgnoreArg_sclPin(UNITY_LINE_TYPE cmock_line);
#define matInitializeBus1_Ignore() TEST_FAIL_MESSAGE("matInitializeBus1 requires _IgnoreAndReturn");
#define matInitializeBus1_IgnoreAndReturn(cmock_retval) matInitializeBus1_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matInitializeBus1_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matInitializeBus1_StopIgnore() matInitializeBus1_CMockStopIgnore()
void matInitializeBus1_CMockStopIgnore(void);
#define matInitializeBus1_Expect(port, sdaPin, sclPin) TEST_FAIL_MESSAGE("matInitializeBus1 requires _ExpectAndReturn");
#define matInitializeBus1_ExpectAndReturn(port, sdaPin, sclPin, cmock_retval) matInitializeBus1_CMockExpectAndReturn(__LINE__, port, sdaPin, sclPin, cmock_retval)
void matInitializeBus1_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, i2c_port_num_t port, gpio_num_t sdaPin, gpio_num_t sclPin, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matInitializeBus1_CALLBACK)(i2c_port_num_t port, gpio_num_t sdaPin, gpio_num_t sclPin, int cmock_num_calls);
void matInitializeBus1_AddCallback(CMOCK_matInitializeBus1_CALLBACK Callback);
void matInitializeBus1_Stub(CMOCK_matInitializeBus1_CALLBACK Callback);
#define matInitializeBus1_StubWithCallback matInitializeBus1_Stub
#define matInitializeBus1_IgnoreArg_port() matInitializeBus1_CMockIgnoreArg_port(__LINE__)
void matInitializeBus1_CMockIgnoreArg_port(UNITY_LINE_TYPE cmock_line);
#define matInitializeBus1_IgnoreArg_sdaPin() matInitializeBus1_CMockIgnoreArg_sdaPin(__LINE__)
void matInitializeBus1_CMockIgnoreArg_sdaPin(UNITY_LINE_TYPE cmock_line);
#define matInitializeBus1_IgnoreArg_sclPin() matInitializeBus1_CMockIgnoreArg_sclPin(__LINE__)
void matInitializeBus1_CMockIgnoreArg_sclPin(UNITY_LINE_TYPE cmock_line);
#define matInitializeBus2_Ignore() TEST_FAIL_MESSAGE("matInitializeBus2 requires _IgnoreAndReturn");
#define matInitializeBus2_IgnoreAndReturn(cmock_retval) matInitializeBus2_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matInitializeBus2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matInitializeBus2_StopIgnore() matInitializeBus2_CMockStopIgnore()
void matInitializeBus2_CMockStopIgnore(void);
#define matInitializeBus2_Expect(port, sdaPin, sclPin) TEST_FAIL_MESSAGE("matInitializeBus2 requires _ExpectAndReturn");
#define matInitializeBus2_ExpectAndReturn(port, sdaPin, sclPin, cmock_retval) matInitializeBus2_CMockExpectAndReturn(__LINE__, port, sdaPin, sclPin, cmock_retval)
void matInitializeBus2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, i2c_port_num_t port, gpio_num_t sdaPin, gpio_num_t sclPin, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matInitializeBus2_CALLBACK)(i2c_port_num_t port, gpio_num_t sdaPin, gpio_num_t sclPin, int cmock_num_calls);
void matInitializeBus2_AddCallback(CMOCK_matInitializeBus2_CALLBACK Callback);
void matInitializeBus2_Stub(CMOCK_matInitializeBus2_CALLBACK Callback);
#define matInitializeBus2_StubWithCallback matInitializeBus2_Stub
#define matInitializeBus2_IgnoreArg_port() matInitializeBus2_CMockIgnoreArg_port(__LINE__)
void matInitializeBus2_CMockIgnoreArg_port(UNITY_LINE_TYPE cmock_line);
#define matInitializeBus2_IgnoreArg_sdaPin() matInitializeBus2_CMockIgnoreArg_sdaPin(__LINE__)
void matInitializeBus2_CMockIgnoreArg_sdaPin(UNITY_LINE_TYPE cmock_line);
#define matInitializeBus2_IgnoreArg_sclPin() matInitializeBus2_CMockIgnoreArg_sclPin(__LINE__)
void matInitializeBus2_CMockIgnoreArg_sclPin(UNITY_LINE_TYPE cmock_line);
#define matSetGCCByAmbientLight_Ignore() TEST_FAIL_MESSAGE("matSetGCCByAmbientLight requires _IgnoreAndReturn");
#define matSetGCCByAmbientLight_IgnoreAndReturn(cmock_retval) matSetGCCByAmbientLight_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void matSetGCCByAmbientLight_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define matSetGCCByAmbientLight_StopIgnore() matSetGCCByAmbientLight_CMockStopIgnore()
void matSetGCCByAmbientLight_CMockStopIgnore(void);
#define matSetGCCByAmbientLight_Expect() TEST_FAIL_MESSAGE("matSetGCCByAmbientLight requires _ExpectAndReturn");
#define matSetGCCByAmbientLight_ExpectAndReturn(cmock_retval) matSetGCCByAmbientLight_CMockExpectAndReturn(__LINE__, cmock_retval)
void matSetGCCByAmbientLight_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_matSetGCCByAmbientLight_CALLBACK)(int cmock_num_calls);
void matSetGCCByAmbientLight_AddCallback(CMOCK_matSetGCCByAmbientLight_CALLBACK Callback);
void matSetGCCByAmbientLight_Stub(CMOCK_matSetGCCByAmbientLight_CALLBACK Callback);
#define matSetGCCByAmbientLight_StubWithCallback matSetGCCByAmbientLight_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
