/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKHTTP_WRAP_H
#define _MOCKHTTP_WRAP_H

#include "unity.h"
#include "http_wrap.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockhttp_wrap_Init(void);
void Mockhttp_wrap_Destroy(void);
void Mockhttp_wrap_Verify(void);




#define wrap_http_client_open_Ignore() TEST_FAIL_MESSAGE("wrap_http_client_open requires _IgnoreAndReturn");
#define wrap_http_client_open_IgnoreAndReturn(cmock_retval) wrap_http_client_open_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void wrap_http_client_open_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define wrap_http_client_open_StopIgnore() wrap_http_client_open_CMockStopIgnore()
void wrap_http_client_open_CMockStopIgnore(void);
#define wrap_http_client_open_Expect(client, write_len) TEST_FAIL_MESSAGE("wrap_http_client_open requires _ExpectAndReturn");
#define wrap_http_client_open_ExpectAndReturn(client, write_len, cmock_retval) wrap_http_client_open_CMockExpectAndReturn(__LINE__, client, write_len, cmock_retval)
void wrap_http_client_open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, int write_len, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_wrap_http_client_open_CALLBACK)(esp_http_client_handle_t client, int write_len, int cmock_num_calls);
void wrap_http_client_open_AddCallback(CMOCK_wrap_http_client_open_CALLBACK Callback);
void wrap_http_client_open_Stub(CMOCK_wrap_http_client_open_CALLBACK Callback);
#define wrap_http_client_open_StubWithCallback wrap_http_client_open_Stub
#define wrap_http_client_read_Ignore() TEST_FAIL_MESSAGE("wrap_http_client_read requires _IgnoreAndReturn");
#define wrap_http_client_read_IgnoreAndReturn(cmock_retval) wrap_http_client_read_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void wrap_http_client_read_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define wrap_http_client_read_StopIgnore() wrap_http_client_read_CMockStopIgnore()
void wrap_http_client_read_CMockStopIgnore(void);
#define wrap_http_client_read_Expect(client, buffer, len) TEST_FAIL_MESSAGE("wrap_http_client_read requires _ExpectAndReturn");
#define wrap_http_client_read_ExpectAndReturn(client, buffer, len, cmock_retval) wrap_http_client_read_CMockExpectAndReturn(__LINE__, client, buffer, len, cmock_retval)
void wrap_http_client_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, char* buffer, int len, int cmock_to_return);
typedef int (* CMOCK_wrap_http_client_read_CALLBACK)(esp_http_client_handle_t client, char* buffer, int len, int cmock_num_calls);
void wrap_http_client_read_AddCallback(CMOCK_wrap_http_client_read_CALLBACK Callback);
void wrap_http_client_read_Stub(CMOCK_wrap_http_client_read_CALLBACK Callback);
#define wrap_http_client_read_StubWithCallback wrap_http_client_read_Stub
#define wrap_http_client_set_url_Ignore() TEST_FAIL_MESSAGE("wrap_http_client_set_url requires _IgnoreAndReturn");
#define wrap_http_client_set_url_IgnoreAndReturn(cmock_retval) wrap_http_client_set_url_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void wrap_http_client_set_url_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define wrap_http_client_set_url_StopIgnore() wrap_http_client_set_url_CMockStopIgnore()
void wrap_http_client_set_url_CMockStopIgnore(void);
#define wrap_http_client_set_url_Expect() TEST_FAIL_MESSAGE("wrap_http_client_set_url requires _ExpectAndReturn");
#define wrap_http_client_set_url_ExpectAndReturn(cmock_retval) wrap_http_client_set_url_CMockExpectAndReturn(__LINE__, cmock_retval)
void wrap_http_client_set_url_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_wrap_http_client_set_url_CALLBACK)(int cmock_num_calls);
void wrap_http_client_set_url_AddCallback(CMOCK_wrap_http_client_set_url_CALLBACK Callback);
void wrap_http_client_set_url_Stub(CMOCK_wrap_http_client_set_url_CALLBACK Callback);
#define wrap_http_client_set_url_StubWithCallback wrap_http_client_set_url_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
