/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockhttp_wrap.h"

static const char* CMockString_buffer = "buffer";
static const char* CMockString_client = "client";
static const char* CMockString_config = "config";
static const char* CMockString_len = "len";
static const char* CMockString_url = "url";
static const char* CMockString_wrap_http_client_cleanup = "wrap_http_client_cleanup";
static const char* CMockString_wrap_http_client_close = "wrap_http_client_close";
static const char* CMockString_wrap_http_client_fetch_headers = "wrap_http_client_fetch_headers";
static const char* CMockString_wrap_http_client_flush_response = "wrap_http_client_flush_response";
static const char* CMockString_wrap_http_client_get_status_code = "wrap_http_client_get_status_code";
static const char* CMockString_wrap_http_client_init = "wrap_http_client_init";
static const char* CMockString_wrap_http_client_open = "wrap_http_client_open";
static const char* CMockString_wrap_http_client_read = "wrap_http_client_read";
static const char* CMockString_wrap_http_client_set_url = "wrap_http_client_set_url";
static const char* CMockString_write_len = "write_len";

typedef struct _CMOCK_wrap_http_client_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_http_client_handle_t ReturnVal;
  const esp_http_client_config_t* Expected_config;

} CMOCK_wrap_http_client_init_CALL_INSTANCE;

typedef struct _CMOCK_wrap_http_client_open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  esp_http_client_handle_t Expected_client;
  int Expected_write_len;

} CMOCK_wrap_http_client_open_CALL_INSTANCE;

typedef struct _CMOCK_wrap_http_client_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  esp_http_client_handle_t Expected_client;
  char* Expected_buffer;
  int Expected_len;

} CMOCK_wrap_http_client_read_CALL_INSTANCE;

typedef struct _CMOCK_wrap_http_client_set_url_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  esp_http_client_handle_t Expected_client;
  const char* Expected_url;

} CMOCK_wrap_http_client_set_url_CALL_INSTANCE;

typedef struct _CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int64_t ReturnVal;
  esp_http_client_handle_t Expected_client;

} CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE;

typedef struct _CMOCK_wrap_http_client_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  esp_http_client_handle_t Expected_client;

} CMOCK_wrap_http_client_close_CALL_INSTANCE;

typedef struct _CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  esp_http_client_handle_t Expected_client;

} CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE;

typedef struct _CMOCK_wrap_http_client_flush_response_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  esp_http_client_handle_t Expected_client;
  int* Expected_len;

} CMOCK_wrap_http_client_flush_response_CALL_INSTANCE;

typedef struct _CMOCK_wrap_http_client_cleanup_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  esp_http_client_handle_t Expected_client;

} CMOCK_wrap_http_client_cleanup_CALL_INSTANCE;

static struct Mockhttp_wrapInstance
{
  char wrap_http_client_init_IgnoreBool;
  esp_http_client_handle_t wrap_http_client_init_FinalReturn;
  char wrap_http_client_init_CallbackBool;
  CMOCK_wrap_http_client_init_CALLBACK wrap_http_client_init_CallbackFunctionPointer;
  int wrap_http_client_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE wrap_http_client_init_CallInstance;
  char wrap_http_client_open_IgnoreBool;
  esp_err_t wrap_http_client_open_FinalReturn;
  char wrap_http_client_open_CallbackBool;
  CMOCK_wrap_http_client_open_CALLBACK wrap_http_client_open_CallbackFunctionPointer;
  int wrap_http_client_open_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE wrap_http_client_open_CallInstance;
  char wrap_http_client_read_IgnoreBool;
  int wrap_http_client_read_FinalReturn;
  char wrap_http_client_read_CallbackBool;
  CMOCK_wrap_http_client_read_CALLBACK wrap_http_client_read_CallbackFunctionPointer;
  int wrap_http_client_read_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE wrap_http_client_read_CallInstance;
  char wrap_http_client_set_url_IgnoreBool;
  esp_err_t wrap_http_client_set_url_FinalReturn;
  char wrap_http_client_set_url_CallbackBool;
  CMOCK_wrap_http_client_set_url_CALLBACK wrap_http_client_set_url_CallbackFunctionPointer;
  int wrap_http_client_set_url_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE wrap_http_client_set_url_CallInstance;
  char wrap_http_client_fetch_headers_IgnoreBool;
  int64_t wrap_http_client_fetch_headers_FinalReturn;
  char wrap_http_client_fetch_headers_CallbackBool;
  CMOCK_wrap_http_client_fetch_headers_CALLBACK wrap_http_client_fetch_headers_CallbackFunctionPointer;
  int wrap_http_client_fetch_headers_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE wrap_http_client_fetch_headers_CallInstance;
  char wrap_http_client_close_IgnoreBool;
  esp_err_t wrap_http_client_close_FinalReturn;
  char wrap_http_client_close_CallbackBool;
  CMOCK_wrap_http_client_close_CALLBACK wrap_http_client_close_CallbackFunctionPointer;
  int wrap_http_client_close_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE wrap_http_client_close_CallInstance;
  char wrap_http_client_get_status_code_IgnoreBool;
  int wrap_http_client_get_status_code_FinalReturn;
  char wrap_http_client_get_status_code_CallbackBool;
  CMOCK_wrap_http_client_get_status_code_CALLBACK wrap_http_client_get_status_code_CallbackFunctionPointer;
  int wrap_http_client_get_status_code_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE wrap_http_client_get_status_code_CallInstance;
  char wrap_http_client_flush_response_IgnoreBool;
  esp_err_t wrap_http_client_flush_response_FinalReturn;
  char wrap_http_client_flush_response_CallbackBool;
  CMOCK_wrap_http_client_flush_response_CALLBACK wrap_http_client_flush_response_CallbackFunctionPointer;
  int wrap_http_client_flush_response_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE wrap_http_client_flush_response_CallInstance;
  char wrap_http_client_cleanup_IgnoreBool;
  esp_err_t wrap_http_client_cleanup_FinalReturn;
  char wrap_http_client_cleanup_CallbackBool;
  CMOCK_wrap_http_client_cleanup_CALLBACK wrap_http_client_cleanup_CallbackFunctionPointer;
  int wrap_http_client_cleanup_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE wrap_http_client_cleanup_CallInstance;
} Mock;


void Mockhttp_wrap_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.wrap_http_client_init_CallInstance;
  if (Mock.wrap_http_client_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wrap_http_client_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.wrap_http_client_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.wrap_http_client_open_CallInstance;
  if (Mock.wrap_http_client_open_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wrap_http_client_open);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.wrap_http_client_open_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.wrap_http_client_read_CallInstance;
  if (Mock.wrap_http_client_read_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wrap_http_client_read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.wrap_http_client_read_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.wrap_http_client_set_url_CallInstance;
  if (Mock.wrap_http_client_set_url_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wrap_http_client_set_url);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.wrap_http_client_set_url_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.wrap_http_client_fetch_headers_CallInstance;
  if (Mock.wrap_http_client_fetch_headers_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wrap_http_client_fetch_headers);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.wrap_http_client_fetch_headers_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.wrap_http_client_close_CallInstance;
  if (Mock.wrap_http_client_close_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wrap_http_client_close);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.wrap_http_client_close_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.wrap_http_client_get_status_code_CallInstance;
  if (Mock.wrap_http_client_get_status_code_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wrap_http_client_get_status_code);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.wrap_http_client_get_status_code_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.wrap_http_client_flush_response_CallInstance;
  if (Mock.wrap_http_client_flush_response_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wrap_http_client_flush_response);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.wrap_http_client_flush_response_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.wrap_http_client_cleanup_CallInstance;
  if (Mock.wrap_http_client_cleanup_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wrap_http_client_cleanup);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.wrap_http_client_cleanup_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockhttp_wrap_Init(void)
{
  Mockhttp_wrap_Destroy();
}

void Mockhttp_wrap_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

esp_http_client_handle_t wrap_http_client_init(const esp_http_client_config_t* config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wrap_http_client_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wrap_http_client_init);
  cmock_call_instance = (CMOCK_wrap_http_client_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wrap_http_client_init_CallInstance);
  Mock.wrap_http_client_init_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_init_CallInstance);
  if (Mock.wrap_http_client_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.wrap_http_client_init_FinalReturn;
    memcpy((void*)(&Mock.wrap_http_client_init_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_http_client_handle_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.wrap_http_client_init_CallbackBool &&
      Mock.wrap_http_client_init_CallbackFunctionPointer != NULL)
  {
    esp_http_client_handle_t cmock_cb_ret = Mock.wrap_http_client_init_CallbackFunctionPointer(config, Mock.wrap_http_client_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_init,CMockString_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_config), (void*)(config), sizeof(const esp_http_client_config_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.wrap_http_client_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.wrap_http_client_init_CallbackFunctionPointer(config, Mock.wrap_http_client_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wrap_http_client_init(CMOCK_wrap_http_client_init_CALL_INSTANCE* cmock_call_instance, const esp_http_client_config_t* config);
void CMockExpectParameters_wrap_http_client_init(CMOCK_wrap_http_client_init_CALL_INSTANCE* cmock_call_instance, const esp_http_client_config_t* config)
{
  cmock_call_instance->Expected_config = config;
}

void wrap_http_client_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_init_CALL_INSTANCE));
  CMOCK_wrap_http_client_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_init_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_init_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.wrap_http_client_init_IgnoreBool = (char)1;
}

void wrap_http_client_init_CMockStopIgnore(void)
{
  if(Mock.wrap_http_client_init_IgnoreBool)
    Mock.wrap_http_client_init_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_init_CallInstance);
  Mock.wrap_http_client_init_IgnoreBool = (char)0;
}

void wrap_http_client_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const esp_http_client_config_t* config, esp_http_client_handle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_init_CALL_INSTANCE));
  CMOCK_wrap_http_client_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_init_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_init_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wrap_http_client_init(cmock_call_instance, config);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_http_client_handle_t[sizeof(cmock_to_return) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
}

void wrap_http_client_init_AddCallback(CMOCK_wrap_http_client_init_CALLBACK Callback)
{
  Mock.wrap_http_client_init_IgnoreBool = (char)0;
  Mock.wrap_http_client_init_CallbackBool = (char)1;
  Mock.wrap_http_client_init_CallbackFunctionPointer = Callback;
}

void wrap_http_client_init_Stub(CMOCK_wrap_http_client_init_CALLBACK Callback)
{
  Mock.wrap_http_client_init_IgnoreBool = (char)0;
  Mock.wrap_http_client_init_CallbackBool = (char)0;
  Mock.wrap_http_client_init_CallbackFunctionPointer = Callback;
}

esp_err_t wrap_http_client_open(esp_http_client_handle_t client, int write_len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wrap_http_client_open_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wrap_http_client_open);
  cmock_call_instance = (CMOCK_wrap_http_client_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wrap_http_client_open_CallInstance);
  Mock.wrap_http_client_open_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_open_CallInstance);
  if (Mock.wrap_http_client_open_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.wrap_http_client_open_FinalReturn;
    memcpy((void*)(&Mock.wrap_http_client_open_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.wrap_http_client_open_CallbackBool &&
      Mock.wrap_http_client_open_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.wrap_http_client_open_CallbackFunctionPointer(client, write_len, Mock.wrap_http_client_open_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_open,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_open,CMockString_write_len);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_write_len, write_len, cmock_line, CMockStringMismatch);
  }
  if (Mock.wrap_http_client_open_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.wrap_http_client_open_CallbackFunctionPointer(client, write_len, Mock.wrap_http_client_open_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wrap_http_client_open(CMOCK_wrap_http_client_open_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client, int write_len);
void CMockExpectParameters_wrap_http_client_open(CMOCK_wrap_http_client_open_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client, int write_len)
{
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_write_len = write_len;
}

void wrap_http_client_open_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_open_CALL_INSTANCE));
  CMOCK_wrap_http_client_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_open_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_open_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_open_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.wrap_http_client_open_IgnoreBool = (char)1;
}

void wrap_http_client_open_CMockStopIgnore(void)
{
  if(Mock.wrap_http_client_open_IgnoreBool)
    Mock.wrap_http_client_open_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_open_CallInstance);
  Mock.wrap_http_client_open_IgnoreBool = (char)0;
}

void wrap_http_client_open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, int write_len, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_open_CALL_INSTANCE));
  CMOCK_wrap_http_client_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_open_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_open_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_open_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wrap_http_client_open(cmock_call_instance, client, write_len);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void wrap_http_client_open_AddCallback(CMOCK_wrap_http_client_open_CALLBACK Callback)
{
  Mock.wrap_http_client_open_IgnoreBool = (char)0;
  Mock.wrap_http_client_open_CallbackBool = (char)1;
  Mock.wrap_http_client_open_CallbackFunctionPointer = Callback;
}

void wrap_http_client_open_Stub(CMOCK_wrap_http_client_open_CALLBACK Callback)
{
  Mock.wrap_http_client_open_IgnoreBool = (char)0;
  Mock.wrap_http_client_open_CallbackBool = (char)0;
  Mock.wrap_http_client_open_CallbackFunctionPointer = Callback;
}

int wrap_http_client_read(esp_http_client_handle_t client, char* buffer, int len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wrap_http_client_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wrap_http_client_read);
  cmock_call_instance = (CMOCK_wrap_http_client_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wrap_http_client_read_CallInstance);
  Mock.wrap_http_client_read_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_read_CallInstance);
  if (Mock.wrap_http_client_read_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.wrap_http_client_read_FinalReturn;
    Mock.wrap_http_client_read_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.wrap_http_client_read_CallbackBool &&
      Mock.wrap_http_client_read_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.wrap_http_client_read_CallbackFunctionPointer(client, buffer, len, Mock.wrap_http_client_read_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_read,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_read,CMockString_buffer);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_read,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  if (Mock.wrap_http_client_read_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.wrap_http_client_read_CallbackFunctionPointer(client, buffer, len, Mock.wrap_http_client_read_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wrap_http_client_read(CMOCK_wrap_http_client_read_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client, char* buffer, int len);
void CMockExpectParameters_wrap_http_client_read(CMOCK_wrap_http_client_read_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client, char* buffer, int len)
{
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_len = len;
}

void wrap_http_client_read_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_read_CALL_INSTANCE));
  CMOCK_wrap_http_client_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_read_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_read_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_read_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.wrap_http_client_read_IgnoreBool = (char)1;
}

void wrap_http_client_read_CMockStopIgnore(void)
{
  if(Mock.wrap_http_client_read_IgnoreBool)
    Mock.wrap_http_client_read_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_read_CallInstance);
  Mock.wrap_http_client_read_IgnoreBool = (char)0;
}

void wrap_http_client_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, char* buffer, int len, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_read_CALL_INSTANCE));
  CMOCK_wrap_http_client_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_read_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_read_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_read_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wrap_http_client_read(cmock_call_instance, client, buffer, len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void wrap_http_client_read_AddCallback(CMOCK_wrap_http_client_read_CALLBACK Callback)
{
  Mock.wrap_http_client_read_IgnoreBool = (char)0;
  Mock.wrap_http_client_read_CallbackBool = (char)1;
  Mock.wrap_http_client_read_CallbackFunctionPointer = Callback;
}

void wrap_http_client_read_Stub(CMOCK_wrap_http_client_read_CALLBACK Callback)
{
  Mock.wrap_http_client_read_IgnoreBool = (char)0;
  Mock.wrap_http_client_read_CallbackBool = (char)0;
  Mock.wrap_http_client_read_CallbackFunctionPointer = Callback;
}

esp_err_t wrap_http_client_set_url(esp_http_client_handle_t client, const char* url)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wrap_http_client_set_url_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wrap_http_client_set_url);
  cmock_call_instance = (CMOCK_wrap_http_client_set_url_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wrap_http_client_set_url_CallInstance);
  Mock.wrap_http_client_set_url_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_set_url_CallInstance);
  if (Mock.wrap_http_client_set_url_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.wrap_http_client_set_url_FinalReturn;
    memcpy((void*)(&Mock.wrap_http_client_set_url_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.wrap_http_client_set_url_CallbackBool &&
      Mock.wrap_http_client_set_url_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.wrap_http_client_set_url_CallbackFunctionPointer(client, url, Mock.wrap_http_client_set_url_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_set_url,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_set_url,CMockString_url);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_url, url, cmock_line, CMockStringMismatch);
  }
  if (Mock.wrap_http_client_set_url_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.wrap_http_client_set_url_CallbackFunctionPointer(client, url, Mock.wrap_http_client_set_url_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wrap_http_client_set_url(CMOCK_wrap_http_client_set_url_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client, const char* url);
void CMockExpectParameters_wrap_http_client_set_url(CMOCK_wrap_http_client_set_url_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client, const char* url)
{
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_url = url;
}

void wrap_http_client_set_url_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_set_url_CALL_INSTANCE));
  CMOCK_wrap_http_client_set_url_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_set_url_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_set_url_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_set_url_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_set_url_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.wrap_http_client_set_url_IgnoreBool = (char)1;
}

void wrap_http_client_set_url_CMockStopIgnore(void)
{
  if(Mock.wrap_http_client_set_url_IgnoreBool)
    Mock.wrap_http_client_set_url_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_set_url_CallInstance);
  Mock.wrap_http_client_set_url_IgnoreBool = (char)0;
}

void wrap_http_client_set_url_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, const char* url, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_set_url_CALL_INSTANCE));
  CMOCK_wrap_http_client_set_url_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_set_url_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_set_url_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_set_url_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_set_url_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wrap_http_client_set_url(cmock_call_instance, client, url);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void wrap_http_client_set_url_AddCallback(CMOCK_wrap_http_client_set_url_CALLBACK Callback)
{
  Mock.wrap_http_client_set_url_IgnoreBool = (char)0;
  Mock.wrap_http_client_set_url_CallbackBool = (char)1;
  Mock.wrap_http_client_set_url_CallbackFunctionPointer = Callback;
}

void wrap_http_client_set_url_Stub(CMOCK_wrap_http_client_set_url_CALLBACK Callback)
{
  Mock.wrap_http_client_set_url_IgnoreBool = (char)0;
  Mock.wrap_http_client_set_url_CallbackBool = (char)0;
  Mock.wrap_http_client_set_url_CallbackFunctionPointer = Callback;
}

int64_t wrap_http_client_fetch_headers(esp_http_client_handle_t client)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wrap_http_client_fetch_headers);
  cmock_call_instance = (CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wrap_http_client_fetch_headers_CallInstance);
  Mock.wrap_http_client_fetch_headers_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_fetch_headers_CallInstance);
  if (Mock.wrap_http_client_fetch_headers_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.wrap_http_client_fetch_headers_FinalReturn;
    memcpy((void*)(&Mock.wrap_http_client_fetch_headers_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(int64_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(int64_t) ? 1 : -1])); /* add int64_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.wrap_http_client_fetch_headers_CallbackBool &&
      Mock.wrap_http_client_fetch_headers_CallbackFunctionPointer != NULL)
  {
    int64_t cmock_cb_ret = Mock.wrap_http_client_fetch_headers_CallbackFunctionPointer(client, Mock.wrap_http_client_fetch_headers_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_fetch_headers,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.wrap_http_client_fetch_headers_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.wrap_http_client_fetch_headers_CallbackFunctionPointer(client, Mock.wrap_http_client_fetch_headers_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wrap_http_client_fetch_headers(CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client);
void CMockExpectParameters_wrap_http_client_fetch_headers(CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client)
{
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
}

void wrap_http_client_fetch_headers_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE));
  CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_fetch_headers_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_fetch_headers_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_fetch_headers_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.wrap_http_client_fetch_headers_IgnoreBool = (char)1;
}

void wrap_http_client_fetch_headers_CMockStopIgnore(void)
{
  if(Mock.wrap_http_client_fetch_headers_IgnoreBool)
    Mock.wrap_http_client_fetch_headers_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_fetch_headers_CallInstance);
  Mock.wrap_http_client_fetch_headers_IgnoreBool = (char)0;
}

void wrap_http_client_fetch_headers_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, int64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE));
  CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_fetch_headers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_fetch_headers_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_fetch_headers_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_fetch_headers_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wrap_http_client_fetch_headers(cmock_call_instance, client);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(int64_t[sizeof(cmock_to_return) == sizeof(int64_t) ? 1 : -1])); /* add int64_t to :treat_as_array if this causes an error */
}

void wrap_http_client_fetch_headers_AddCallback(CMOCK_wrap_http_client_fetch_headers_CALLBACK Callback)
{
  Mock.wrap_http_client_fetch_headers_IgnoreBool = (char)0;
  Mock.wrap_http_client_fetch_headers_CallbackBool = (char)1;
  Mock.wrap_http_client_fetch_headers_CallbackFunctionPointer = Callback;
}

void wrap_http_client_fetch_headers_Stub(CMOCK_wrap_http_client_fetch_headers_CALLBACK Callback)
{
  Mock.wrap_http_client_fetch_headers_IgnoreBool = (char)0;
  Mock.wrap_http_client_fetch_headers_CallbackBool = (char)0;
  Mock.wrap_http_client_fetch_headers_CallbackFunctionPointer = Callback;
}

esp_err_t wrap_http_client_close(esp_http_client_handle_t client)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wrap_http_client_close_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wrap_http_client_close);
  cmock_call_instance = (CMOCK_wrap_http_client_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wrap_http_client_close_CallInstance);
  Mock.wrap_http_client_close_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_close_CallInstance);
  if (Mock.wrap_http_client_close_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.wrap_http_client_close_FinalReturn;
    memcpy((void*)(&Mock.wrap_http_client_close_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.wrap_http_client_close_CallbackBool &&
      Mock.wrap_http_client_close_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.wrap_http_client_close_CallbackFunctionPointer(client, Mock.wrap_http_client_close_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_close,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.wrap_http_client_close_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.wrap_http_client_close_CallbackFunctionPointer(client, Mock.wrap_http_client_close_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wrap_http_client_close(CMOCK_wrap_http_client_close_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client);
void CMockExpectParameters_wrap_http_client_close(CMOCK_wrap_http_client_close_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client)
{
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
}

void wrap_http_client_close_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_close_CALL_INSTANCE));
  CMOCK_wrap_http_client_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_close_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_close_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_close_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.wrap_http_client_close_IgnoreBool = (char)1;
}

void wrap_http_client_close_CMockStopIgnore(void)
{
  if(Mock.wrap_http_client_close_IgnoreBool)
    Mock.wrap_http_client_close_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_close_CallInstance);
  Mock.wrap_http_client_close_IgnoreBool = (char)0;
}

void wrap_http_client_close_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_close_CALL_INSTANCE));
  CMOCK_wrap_http_client_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_close_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_close_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_close_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wrap_http_client_close(cmock_call_instance, client);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void wrap_http_client_close_AddCallback(CMOCK_wrap_http_client_close_CALLBACK Callback)
{
  Mock.wrap_http_client_close_IgnoreBool = (char)0;
  Mock.wrap_http_client_close_CallbackBool = (char)1;
  Mock.wrap_http_client_close_CallbackFunctionPointer = Callback;
}

void wrap_http_client_close_Stub(CMOCK_wrap_http_client_close_CALLBACK Callback)
{
  Mock.wrap_http_client_close_IgnoreBool = (char)0;
  Mock.wrap_http_client_close_CallbackBool = (char)0;
  Mock.wrap_http_client_close_CallbackFunctionPointer = Callback;
}

int wrap_http_client_get_status_code(esp_http_client_handle_t client)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wrap_http_client_get_status_code);
  cmock_call_instance = (CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wrap_http_client_get_status_code_CallInstance);
  Mock.wrap_http_client_get_status_code_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_get_status_code_CallInstance);
  if (Mock.wrap_http_client_get_status_code_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.wrap_http_client_get_status_code_FinalReturn;
    Mock.wrap_http_client_get_status_code_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.wrap_http_client_get_status_code_CallbackBool &&
      Mock.wrap_http_client_get_status_code_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.wrap_http_client_get_status_code_CallbackFunctionPointer(client, Mock.wrap_http_client_get_status_code_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_get_status_code,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.wrap_http_client_get_status_code_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.wrap_http_client_get_status_code_CallbackFunctionPointer(client, Mock.wrap_http_client_get_status_code_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wrap_http_client_get_status_code(CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client);
void CMockExpectParameters_wrap_http_client_get_status_code(CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client)
{
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
}

void wrap_http_client_get_status_code_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE));
  CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_get_status_code_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_get_status_code_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_get_status_code_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.wrap_http_client_get_status_code_IgnoreBool = (char)1;
}

void wrap_http_client_get_status_code_CMockStopIgnore(void)
{
  if(Mock.wrap_http_client_get_status_code_IgnoreBool)
    Mock.wrap_http_client_get_status_code_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_get_status_code_CallInstance);
  Mock.wrap_http_client_get_status_code_IgnoreBool = (char)0;
}

void wrap_http_client_get_status_code_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE));
  CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_get_status_code_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_get_status_code_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_get_status_code_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_get_status_code_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wrap_http_client_get_status_code(cmock_call_instance, client);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void wrap_http_client_get_status_code_AddCallback(CMOCK_wrap_http_client_get_status_code_CALLBACK Callback)
{
  Mock.wrap_http_client_get_status_code_IgnoreBool = (char)0;
  Mock.wrap_http_client_get_status_code_CallbackBool = (char)1;
  Mock.wrap_http_client_get_status_code_CallbackFunctionPointer = Callback;
}

void wrap_http_client_get_status_code_Stub(CMOCK_wrap_http_client_get_status_code_CALLBACK Callback)
{
  Mock.wrap_http_client_get_status_code_IgnoreBool = (char)0;
  Mock.wrap_http_client_get_status_code_CallbackBool = (char)0;
  Mock.wrap_http_client_get_status_code_CallbackFunctionPointer = Callback;
}

esp_err_t wrap_http_client_flush_response(esp_http_client_handle_t client, int* len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wrap_http_client_flush_response_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wrap_http_client_flush_response);
  cmock_call_instance = (CMOCK_wrap_http_client_flush_response_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wrap_http_client_flush_response_CallInstance);
  Mock.wrap_http_client_flush_response_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_flush_response_CallInstance);
  if (Mock.wrap_http_client_flush_response_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.wrap_http_client_flush_response_FinalReturn;
    memcpy((void*)(&Mock.wrap_http_client_flush_response_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.wrap_http_client_flush_response_CallbackBool &&
      Mock.wrap_http_client_flush_response_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.wrap_http_client_flush_response_CallbackFunctionPointer(client, len, Mock.wrap_http_client_flush_response_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_flush_response,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_flush_response,CMockString_len);
    if (cmock_call_instance->Expected_len == NULL)
      { UNITY_TEST_ASSERT_NULL(len, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_len, len, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.wrap_http_client_flush_response_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.wrap_http_client_flush_response_CallbackFunctionPointer(client, len, Mock.wrap_http_client_flush_response_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wrap_http_client_flush_response(CMOCK_wrap_http_client_flush_response_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client, int* len);
void CMockExpectParameters_wrap_http_client_flush_response(CMOCK_wrap_http_client_flush_response_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client, int* len)
{
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_len = len;
}

void wrap_http_client_flush_response_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_flush_response_CALL_INSTANCE));
  CMOCK_wrap_http_client_flush_response_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_flush_response_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_flush_response_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_flush_response_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_flush_response_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.wrap_http_client_flush_response_IgnoreBool = (char)1;
}

void wrap_http_client_flush_response_CMockStopIgnore(void)
{
  if(Mock.wrap_http_client_flush_response_IgnoreBool)
    Mock.wrap_http_client_flush_response_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_flush_response_CallInstance);
  Mock.wrap_http_client_flush_response_IgnoreBool = (char)0;
}

void wrap_http_client_flush_response_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, int* len, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_flush_response_CALL_INSTANCE));
  CMOCK_wrap_http_client_flush_response_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_flush_response_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_flush_response_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_flush_response_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_flush_response_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wrap_http_client_flush_response(cmock_call_instance, client, len);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void wrap_http_client_flush_response_AddCallback(CMOCK_wrap_http_client_flush_response_CALLBACK Callback)
{
  Mock.wrap_http_client_flush_response_IgnoreBool = (char)0;
  Mock.wrap_http_client_flush_response_CallbackBool = (char)1;
  Mock.wrap_http_client_flush_response_CallbackFunctionPointer = Callback;
}

void wrap_http_client_flush_response_Stub(CMOCK_wrap_http_client_flush_response_CALLBACK Callback)
{
  Mock.wrap_http_client_flush_response_IgnoreBool = (char)0;
  Mock.wrap_http_client_flush_response_CallbackBool = (char)0;
  Mock.wrap_http_client_flush_response_CallbackFunctionPointer = Callback;
}

esp_err_t wrap_http_client_cleanup(esp_http_client_handle_t client)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wrap_http_client_cleanup_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wrap_http_client_cleanup);
  cmock_call_instance = (CMOCK_wrap_http_client_cleanup_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wrap_http_client_cleanup_CallInstance);
  Mock.wrap_http_client_cleanup_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_cleanup_CallInstance);
  if (Mock.wrap_http_client_cleanup_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.wrap_http_client_cleanup_FinalReturn;
    memcpy((void*)(&Mock.wrap_http_client_cleanup_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.wrap_http_client_cleanup_CallbackBool &&
      Mock.wrap_http_client_cleanup_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.wrap_http_client_cleanup_CallbackFunctionPointer(client, Mock.wrap_http_client_cleanup_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wrap_http_client_cleanup,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.wrap_http_client_cleanup_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.wrap_http_client_cleanup_CallbackFunctionPointer(client, Mock.wrap_http_client_cleanup_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wrap_http_client_cleanup(CMOCK_wrap_http_client_cleanup_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client);
void CMockExpectParameters_wrap_http_client_cleanup(CMOCK_wrap_http_client_cleanup_CALL_INSTANCE* cmock_call_instance, esp_http_client_handle_t client)
{
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
}

void wrap_http_client_cleanup_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_cleanup_CALL_INSTANCE));
  CMOCK_wrap_http_client_cleanup_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_cleanup_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_cleanup_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_cleanup_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_cleanup_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.wrap_http_client_cleanup_IgnoreBool = (char)1;
}

void wrap_http_client_cleanup_CMockStopIgnore(void)
{
  if(Mock.wrap_http_client_cleanup_IgnoreBool)
    Mock.wrap_http_client_cleanup_CallInstance = CMock_Guts_MemNext(Mock.wrap_http_client_cleanup_CallInstance);
  Mock.wrap_http_client_cleanup_IgnoreBool = (char)0;
}

void wrap_http_client_cleanup_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_http_client_handle_t client, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wrap_http_client_cleanup_CALL_INSTANCE));
  CMOCK_wrap_http_client_cleanup_CALL_INSTANCE* cmock_call_instance = (CMOCK_wrap_http_client_cleanup_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wrap_http_client_cleanup_CallInstance = CMock_Guts_MemChain(Mock.wrap_http_client_cleanup_CallInstance, cmock_guts_index);
  Mock.wrap_http_client_cleanup_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wrap_http_client_cleanup(cmock_call_instance, client);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void wrap_http_client_cleanup_AddCallback(CMOCK_wrap_http_client_cleanup_CALLBACK Callback)
{
  Mock.wrap_http_client_cleanup_IgnoreBool = (char)0;
  Mock.wrap_http_client_cleanup_CallbackBool = (char)1;
  Mock.wrap_http_client_cleanup_CallbackFunctionPointer = Callback;
}

void wrap_http_client_cleanup_Stub(CMOCK_wrap_http_client_cleanup_CALLBACK Callback)
{
  Mock.wrap_http_client_cleanup_IgnoreBool = (char)0;
  Mock.wrap_http_client_cleanup_CallbackBool = (char)0;
  Mock.wrap_http_client_cleanup_CallbackFunctionPointer = Callback;
}

