/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocktraffic_data.h"

static const char* CMockString_borrowTrafficData = "borrowTrafficData";
static const char* CMockString_category = "category";
static const char* CMockString_copyTrafficData = "copyTrafficData";
static const char* CMockString_data = "data";
static const char* CMockString_dataSize = "dataSize";
static const char* CMockString_dir = "dir";
static const char* CMockString_initTrafficData = "initTrafficData";
static const char* CMockString_out = "out";
static const char* CMockString_outLen = "outLen";
static const char* CMockString_releaseTrafficData = "releaseTrafficData";
static const char* CMockString_updateTrafficData = "updateTrafficData";
static const char* CMockString_xTicksToWait = "xTicksToWait";

typedef struct _CMOCK_initTrafficData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;

} CMOCK_initTrafficData_CALL_INSTANCE;

typedef struct _CMOCK_borrowTrafficData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  SpeedCategory Expected_category;
  TickType_t Expected_xTicksToWait;
  char IgnoreArg_category;
  char IgnoreArg_xTicksToWait;

} CMOCK_borrowTrafficData_CALL_INSTANCE;

typedef struct _CMOCK_releaseTrafficData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  SpeedCategory Expected_category;
  char IgnoreArg_category;

} CMOCK_releaseTrafficData_CALL_INSTANCE;

typedef struct _CMOCK_updateTrafficData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  LEDData* Expected_data;
  size_t Expected_dataSize;
  Direction Expected_dir;
  SpeedCategory Expected_category;
  char ReturnThruPtr_data_Used;
  LEDData const* ReturnThruPtr_data_Val;
  size_t ReturnThruPtr_data_Size;
  char IgnoreArg_data;
  char IgnoreArg_dataSize;
  char IgnoreArg_dir;
  char IgnoreArg_category;

} CMOCK_updateTrafficData_CALL_INSTANCE;

typedef struct _CMOCK_copyTrafficData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  LEDData* Expected_out;
  size_t Expected_outLen;
  Direction Expected_dir;
  SpeedCategory Expected_category;
  char ReturnThruPtr_out_Used;
  LEDData const* ReturnThruPtr_out_Val;
  size_t ReturnThruPtr_out_Size;
  char IgnoreArg_out;
  char IgnoreArg_outLen;
  char IgnoreArg_dir;
  char IgnoreArg_category;

} CMOCK_copyTrafficData_CALL_INSTANCE;

static struct Mocktraffic_dataInstance
{
  char initTrafficData_IgnoreBool;
  esp_err_t initTrafficData_FinalReturn;
  char initTrafficData_CallbackBool;
  CMOCK_initTrafficData_CALLBACK initTrafficData_CallbackFunctionPointer;
  int initTrafficData_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE initTrafficData_CallInstance;
  char borrowTrafficData_IgnoreBool;
  esp_err_t borrowTrafficData_FinalReturn;
  char borrowTrafficData_CallbackBool;
  CMOCK_borrowTrafficData_CALLBACK borrowTrafficData_CallbackFunctionPointer;
  int borrowTrafficData_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE borrowTrafficData_CallInstance;
  char releaseTrafficData_IgnoreBool;
  esp_err_t releaseTrafficData_FinalReturn;
  char releaseTrafficData_CallbackBool;
  CMOCK_releaseTrafficData_CALLBACK releaseTrafficData_CallbackFunctionPointer;
  int releaseTrafficData_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE releaseTrafficData_CallInstance;
  char updateTrafficData_IgnoreBool;
  esp_err_t updateTrafficData_FinalReturn;
  char updateTrafficData_CallbackBool;
  CMOCK_updateTrafficData_CALLBACK updateTrafficData_CallbackFunctionPointer;
  int updateTrafficData_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE updateTrafficData_CallInstance;
  char copyTrafficData_IgnoreBool;
  esp_err_t copyTrafficData_FinalReturn;
  char copyTrafficData_CallbackBool;
  CMOCK_copyTrafficData_CALLBACK copyTrafficData_CallbackFunctionPointer;
  int copyTrafficData_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE copyTrafficData_CallInstance;
} Mock;


void Mocktraffic_data_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.initTrafficData_CallInstance;
  if (Mock.initTrafficData_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_initTrafficData);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.initTrafficData_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.borrowTrafficData_CallInstance;
  if (Mock.borrowTrafficData_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_borrowTrafficData);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.borrowTrafficData_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.releaseTrafficData_CallInstance;
  if (Mock.releaseTrafficData_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_releaseTrafficData);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.releaseTrafficData_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.updateTrafficData_CallInstance;
  if (Mock.updateTrafficData_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_updateTrafficData);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.updateTrafficData_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.copyTrafficData_CallInstance;
  if (Mock.copyTrafficData_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_copyTrafficData);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.copyTrafficData_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mocktraffic_data_Init(void)
{
  Mocktraffic_data_Destroy();
}

void Mocktraffic_data_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

esp_err_t initTrafficData(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_initTrafficData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_initTrafficData);
  cmock_call_instance = (CMOCK_initTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.initTrafficData_CallInstance);
  Mock.initTrafficData_CallInstance = CMock_Guts_MemNext(Mock.initTrafficData_CallInstance);
  if (Mock.initTrafficData_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.initTrafficData_FinalReturn;
    memcpy((void*)(&Mock.initTrafficData_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.initTrafficData_CallbackBool &&
      Mock.initTrafficData_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.initTrafficData_CallbackFunctionPointer(Mock.initTrafficData_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.initTrafficData_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.initTrafficData_CallbackFunctionPointer(Mock.initTrafficData_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void initTrafficData_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_initTrafficData_CALL_INSTANCE));
  CMOCK_initTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_initTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.initTrafficData_CallInstance = CMock_Guts_MemChain(Mock.initTrafficData_CallInstance, cmock_guts_index);
  Mock.initTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.initTrafficData_IgnoreBool = (char)1;
}

void initTrafficData_CMockStopIgnore(void)
{
  if(Mock.initTrafficData_IgnoreBool)
    Mock.initTrafficData_CallInstance = CMock_Guts_MemNext(Mock.initTrafficData_CallInstance);
  Mock.initTrafficData_IgnoreBool = (char)0;
}

void initTrafficData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_initTrafficData_CALL_INSTANCE));
  CMOCK_initTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_initTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.initTrafficData_CallInstance = CMock_Guts_MemChain(Mock.initTrafficData_CallInstance, cmock_guts_index);
  Mock.initTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void initTrafficData_AddCallback(CMOCK_initTrafficData_CALLBACK Callback)
{
  Mock.initTrafficData_IgnoreBool = (char)0;
  Mock.initTrafficData_CallbackBool = (char)1;
  Mock.initTrafficData_CallbackFunctionPointer = Callback;
}

void initTrafficData_Stub(CMOCK_initTrafficData_CALLBACK Callback)
{
  Mock.initTrafficData_IgnoreBool = (char)0;
  Mock.initTrafficData_CallbackBool = (char)0;
  Mock.initTrafficData_CallbackFunctionPointer = Callback;
}

esp_err_t borrowTrafficData(SpeedCategory category, TickType_t xTicksToWait)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_borrowTrafficData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_borrowTrafficData);
  cmock_call_instance = (CMOCK_borrowTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.borrowTrafficData_CallInstance);
  Mock.borrowTrafficData_CallInstance = CMock_Guts_MemNext(Mock.borrowTrafficData_CallInstance);
  if (Mock.borrowTrafficData_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.borrowTrafficData_FinalReturn;
    memcpy((void*)(&Mock.borrowTrafficData_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.borrowTrafficData_CallbackBool &&
      Mock.borrowTrafficData_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.borrowTrafficData_CallbackFunctionPointer(category, xTicksToWait, Mock.borrowTrafficData_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_category)
  {
    UNITY_SET_DETAILS(CMockString_borrowTrafficData,CMockString_category);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_category), (void*)(&category), sizeof(SpeedCategory), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_xTicksToWait)
  {
    UNITY_SET_DETAILS(CMockString_borrowTrafficData,CMockString_xTicksToWait);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_xTicksToWait), (void*)(&xTicksToWait), sizeof(TickType_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.borrowTrafficData_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.borrowTrafficData_CallbackFunctionPointer(category, xTicksToWait, Mock.borrowTrafficData_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_borrowTrafficData(CMOCK_borrowTrafficData_CALL_INSTANCE* cmock_call_instance, SpeedCategory category, TickType_t xTicksToWait);
void CMockExpectParameters_borrowTrafficData(CMOCK_borrowTrafficData_CALL_INSTANCE* cmock_call_instance, SpeedCategory category, TickType_t xTicksToWait)
{
  memcpy((void*)(&cmock_call_instance->Expected_category), (const void*)(&category),
         sizeof(SpeedCategory[sizeof(category) == sizeof(SpeedCategory) ? 1 : -1])); /* add SpeedCategory to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_category = 0;
  memcpy((void*)(&cmock_call_instance->Expected_xTicksToWait), (const void*)(&xTicksToWait),
         sizeof(TickType_t[sizeof(xTicksToWait) == sizeof(TickType_t) ? 1 : -1])); /* add TickType_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_xTicksToWait = 0;
}

void borrowTrafficData_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_borrowTrafficData_CALL_INSTANCE));
  CMOCK_borrowTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_borrowTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.borrowTrafficData_CallInstance = CMock_Guts_MemChain(Mock.borrowTrafficData_CallInstance, cmock_guts_index);
  Mock.borrowTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.borrowTrafficData_IgnoreBool = (char)1;
}

void borrowTrafficData_CMockStopIgnore(void)
{
  if(Mock.borrowTrafficData_IgnoreBool)
    Mock.borrowTrafficData_CallInstance = CMock_Guts_MemNext(Mock.borrowTrafficData_CallInstance);
  Mock.borrowTrafficData_IgnoreBool = (char)0;
}

void borrowTrafficData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SpeedCategory category, TickType_t xTicksToWait, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_borrowTrafficData_CALL_INSTANCE));
  CMOCK_borrowTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_borrowTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.borrowTrafficData_CallInstance = CMock_Guts_MemChain(Mock.borrowTrafficData_CallInstance, cmock_guts_index);
  Mock.borrowTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_borrowTrafficData(cmock_call_instance, category, xTicksToWait);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void borrowTrafficData_AddCallback(CMOCK_borrowTrafficData_CALLBACK Callback)
{
  Mock.borrowTrafficData_IgnoreBool = (char)0;
  Mock.borrowTrafficData_CallbackBool = (char)1;
  Mock.borrowTrafficData_CallbackFunctionPointer = Callback;
}

void borrowTrafficData_Stub(CMOCK_borrowTrafficData_CALLBACK Callback)
{
  Mock.borrowTrafficData_IgnoreBool = (char)0;
  Mock.borrowTrafficData_CallbackBool = (char)0;
  Mock.borrowTrafficData_CallbackFunctionPointer = Callback;
}

void borrowTrafficData_CMockIgnoreArg_category(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_borrowTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_borrowTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.borrowTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_category = 1;
}

void borrowTrafficData_CMockIgnoreArg_xTicksToWait(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_borrowTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_borrowTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.borrowTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_xTicksToWait = 1;
}

esp_err_t releaseTrafficData(SpeedCategory category)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_releaseTrafficData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_releaseTrafficData);
  cmock_call_instance = (CMOCK_releaseTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.releaseTrafficData_CallInstance);
  Mock.releaseTrafficData_CallInstance = CMock_Guts_MemNext(Mock.releaseTrafficData_CallInstance);
  if (Mock.releaseTrafficData_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.releaseTrafficData_FinalReturn;
    memcpy((void*)(&Mock.releaseTrafficData_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.releaseTrafficData_CallbackBool &&
      Mock.releaseTrafficData_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.releaseTrafficData_CallbackFunctionPointer(category, Mock.releaseTrafficData_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_category)
  {
    UNITY_SET_DETAILS(CMockString_releaseTrafficData,CMockString_category);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_category), (void*)(&category), sizeof(SpeedCategory), cmock_line, CMockStringMismatch);
  }
  if (Mock.releaseTrafficData_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.releaseTrafficData_CallbackFunctionPointer(category, Mock.releaseTrafficData_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_releaseTrafficData(CMOCK_releaseTrafficData_CALL_INSTANCE* cmock_call_instance, SpeedCategory category);
void CMockExpectParameters_releaseTrafficData(CMOCK_releaseTrafficData_CALL_INSTANCE* cmock_call_instance, SpeedCategory category)
{
  memcpy((void*)(&cmock_call_instance->Expected_category), (const void*)(&category),
         sizeof(SpeedCategory[sizeof(category) == sizeof(SpeedCategory) ? 1 : -1])); /* add SpeedCategory to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_category = 0;
}

void releaseTrafficData_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_releaseTrafficData_CALL_INSTANCE));
  CMOCK_releaseTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_releaseTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.releaseTrafficData_CallInstance = CMock_Guts_MemChain(Mock.releaseTrafficData_CallInstance, cmock_guts_index);
  Mock.releaseTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.releaseTrafficData_IgnoreBool = (char)1;
}

void releaseTrafficData_CMockStopIgnore(void)
{
  if(Mock.releaseTrafficData_IgnoreBool)
    Mock.releaseTrafficData_CallInstance = CMock_Guts_MemNext(Mock.releaseTrafficData_CallInstance);
  Mock.releaseTrafficData_IgnoreBool = (char)0;
}

void releaseTrafficData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SpeedCategory category, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_releaseTrafficData_CALL_INSTANCE));
  CMOCK_releaseTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_releaseTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.releaseTrafficData_CallInstance = CMock_Guts_MemChain(Mock.releaseTrafficData_CallInstance, cmock_guts_index);
  Mock.releaseTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_releaseTrafficData(cmock_call_instance, category);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void releaseTrafficData_AddCallback(CMOCK_releaseTrafficData_CALLBACK Callback)
{
  Mock.releaseTrafficData_IgnoreBool = (char)0;
  Mock.releaseTrafficData_CallbackBool = (char)1;
  Mock.releaseTrafficData_CallbackFunctionPointer = Callback;
}

void releaseTrafficData_Stub(CMOCK_releaseTrafficData_CALLBACK Callback)
{
  Mock.releaseTrafficData_IgnoreBool = (char)0;
  Mock.releaseTrafficData_CallbackBool = (char)0;
  Mock.releaseTrafficData_CallbackFunctionPointer = Callback;
}

void releaseTrafficData_CMockIgnoreArg_category(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_releaseTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_releaseTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.releaseTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_category = 1;
}

esp_err_t updateTrafficData(LEDData* data, size_t dataSize, Direction dir, SpeedCategory category)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_updateTrafficData);
  cmock_call_instance = (CMOCK_updateTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.updateTrafficData_CallInstance);
  Mock.updateTrafficData_CallInstance = CMock_Guts_MemNext(Mock.updateTrafficData_CallInstance);
  if (Mock.updateTrafficData_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.updateTrafficData_FinalReturn;
    memcpy((void*)(&Mock.updateTrafficData_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.updateTrafficData_CallbackBool &&
      Mock.updateTrafficData_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.updateTrafficData_CallbackFunctionPointer(data, dataSize, dir, category, Mock.updateTrafficData_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_updateTrafficData,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(LEDData), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dataSize)
  {
    UNITY_SET_DETAILS(CMockString_updateTrafficData,CMockString_dataSize);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dataSize), (void*)(&dataSize), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dir)
  {
    UNITY_SET_DETAILS(CMockString_updateTrafficData,CMockString_dir);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dir), (void*)(&dir), sizeof(Direction), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_category)
  {
    UNITY_SET_DETAILS(CMockString_updateTrafficData,CMockString_category);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_category), (void*)(&category), sizeof(SpeedCategory), cmock_line, CMockStringMismatch);
  }
  if (Mock.updateTrafficData_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.updateTrafficData_CallbackFunctionPointer(data, dataSize, dir, category, Mock.updateTrafficData_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)data, (const void*)cmock_call_instance->ReturnThruPtr_data_Val,
      cmock_call_instance->ReturnThruPtr_data_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_updateTrafficData(CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance, LEDData* data, size_t dataSize, Direction dir, SpeedCategory category);
void CMockExpectParameters_updateTrafficData(CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance, LEDData* data, size_t dataSize, Direction dir, SpeedCategory category)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->ReturnThruPtr_data_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_dataSize), (const void*)(&dataSize),
         sizeof(size_t[sizeof(dataSize) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_dataSize = 0;
  memcpy((void*)(&cmock_call_instance->Expected_dir), (const void*)(&dir),
         sizeof(Direction[sizeof(dir) == sizeof(Direction) ? 1 : -1])); /* add Direction to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_dir = 0;
  memcpy((void*)(&cmock_call_instance->Expected_category), (const void*)(&category),
         sizeof(SpeedCategory[sizeof(category) == sizeof(SpeedCategory) ? 1 : -1])); /* add SpeedCategory to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_category = 0;
}

void updateTrafficData_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_updateTrafficData_CALL_INSTANCE));
  CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_updateTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.updateTrafficData_CallInstance = CMock_Guts_MemChain(Mock.updateTrafficData_CallInstance, cmock_guts_index);
  Mock.updateTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.updateTrafficData_IgnoreBool = (char)1;
}

void updateTrafficData_CMockStopIgnore(void)
{
  if(Mock.updateTrafficData_IgnoreBool)
    Mock.updateTrafficData_CallInstance = CMock_Guts_MemNext(Mock.updateTrafficData_CallInstance);
  Mock.updateTrafficData_IgnoreBool = (char)0;
}

void updateTrafficData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, LEDData* data, size_t dataSize, Direction dir, SpeedCategory category, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_updateTrafficData_CALL_INSTANCE));
  CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_updateTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.updateTrafficData_CallInstance = CMock_Guts_MemChain(Mock.updateTrafficData_CallInstance, cmock_guts_index);
  Mock.updateTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_updateTrafficData(cmock_call_instance, data, dataSize, dir, category);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void updateTrafficData_AddCallback(CMOCK_updateTrafficData_CALLBACK Callback)
{
  Mock.updateTrafficData_IgnoreBool = (char)0;
  Mock.updateTrafficData_CallbackBool = (char)1;
  Mock.updateTrafficData_CallbackFunctionPointer = Callback;
}

void updateTrafficData_Stub(CMOCK_updateTrafficData_CALLBACK Callback)
{
  Mock.updateTrafficData_IgnoreBool = (char)0;
  Mock.updateTrafficData_CallbackBool = (char)0;
  Mock.updateTrafficData_CallbackFunctionPointer = Callback;
}

void updateTrafficData_CMockReturnMemThruPtr_data(UNITY_LINE_TYPE cmock_line, LEDData const* data, size_t cmock_size)
{
  CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_updateTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.updateTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_data_Used = 1;
  cmock_call_instance->ReturnThruPtr_data_Val = data;
  cmock_call_instance->ReturnThruPtr_data_Size = cmock_size;
}

void updateTrafficData_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_updateTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.updateTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

void updateTrafficData_CMockIgnoreArg_dataSize(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_updateTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.updateTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dataSize = 1;
}

void updateTrafficData_CMockIgnoreArg_dir(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_updateTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.updateTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dir = 1;
}

void updateTrafficData_CMockIgnoreArg_category(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_updateTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_updateTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.updateTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_category = 1;
}

esp_err_t copyTrafficData(LEDData* out, size_t outLen, Direction dir, SpeedCategory category)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_copyTrafficData);
  cmock_call_instance = (CMOCK_copyTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.copyTrafficData_CallInstance);
  Mock.copyTrafficData_CallInstance = CMock_Guts_MemNext(Mock.copyTrafficData_CallInstance);
  if (Mock.copyTrafficData_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.copyTrafficData_FinalReturn;
    memcpy((void*)(&Mock.copyTrafficData_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.copyTrafficData_CallbackBool &&
      Mock.copyTrafficData_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.copyTrafficData_CallbackFunctionPointer(out, outLen, dir, category, Mock.copyTrafficData_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_out)
  {
    UNITY_SET_DETAILS(CMockString_copyTrafficData,CMockString_out);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_out), (void*)(out), sizeof(LEDData), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_outLen)
  {
    UNITY_SET_DETAILS(CMockString_copyTrafficData,CMockString_outLen);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_outLen), (void*)(&outLen), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dir)
  {
    UNITY_SET_DETAILS(CMockString_copyTrafficData,CMockString_dir);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dir), (void*)(&dir), sizeof(Direction), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_category)
  {
    UNITY_SET_DETAILS(CMockString_copyTrafficData,CMockString_category);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_category), (void*)(&category), sizeof(SpeedCategory), cmock_line, CMockStringMismatch);
  }
  if (Mock.copyTrafficData_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.copyTrafficData_CallbackFunctionPointer(out, outLen, dir, category, Mock.copyTrafficData_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_out_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(out, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)out, (const void*)cmock_call_instance->ReturnThruPtr_out_Val,
      cmock_call_instance->ReturnThruPtr_out_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_copyTrafficData(CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance, LEDData* out, size_t outLen, Direction dir, SpeedCategory category);
void CMockExpectParameters_copyTrafficData(CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance, LEDData* out, size_t outLen, Direction dir, SpeedCategory category)
{
  cmock_call_instance->Expected_out = out;
  cmock_call_instance->IgnoreArg_out = 0;
  cmock_call_instance->ReturnThruPtr_out_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_outLen), (const void*)(&outLen),
         sizeof(size_t[sizeof(outLen) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_outLen = 0;
  memcpy((void*)(&cmock_call_instance->Expected_dir), (const void*)(&dir),
         sizeof(Direction[sizeof(dir) == sizeof(Direction) ? 1 : -1])); /* add Direction to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_dir = 0;
  memcpy((void*)(&cmock_call_instance->Expected_category), (const void*)(&category),
         sizeof(SpeedCategory[sizeof(category) == sizeof(SpeedCategory) ? 1 : -1])); /* add SpeedCategory to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_category = 0;
}

void copyTrafficData_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_copyTrafficData_CALL_INSTANCE));
  CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_copyTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.copyTrafficData_CallInstance = CMock_Guts_MemChain(Mock.copyTrafficData_CallInstance, cmock_guts_index);
  Mock.copyTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.copyTrafficData_IgnoreBool = (char)1;
}

void copyTrafficData_CMockStopIgnore(void)
{
  if(Mock.copyTrafficData_IgnoreBool)
    Mock.copyTrafficData_CallInstance = CMock_Guts_MemNext(Mock.copyTrafficData_CallInstance);
  Mock.copyTrafficData_IgnoreBool = (char)0;
}

void copyTrafficData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, LEDData* out, size_t outLen, Direction dir, SpeedCategory category, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_copyTrafficData_CALL_INSTANCE));
  CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_copyTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.copyTrafficData_CallInstance = CMock_Guts_MemChain(Mock.copyTrafficData_CallInstance, cmock_guts_index);
  Mock.copyTrafficData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_copyTrafficData(cmock_call_instance, out, outLen, dir, category);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void copyTrafficData_AddCallback(CMOCK_copyTrafficData_CALLBACK Callback)
{
  Mock.copyTrafficData_IgnoreBool = (char)0;
  Mock.copyTrafficData_CallbackBool = (char)1;
  Mock.copyTrafficData_CallbackFunctionPointer = Callback;
}

void copyTrafficData_Stub(CMOCK_copyTrafficData_CALLBACK Callback)
{
  Mock.copyTrafficData_IgnoreBool = (char)0;
  Mock.copyTrafficData_CallbackBool = (char)0;
  Mock.copyTrafficData_CallbackFunctionPointer = Callback;
}

void copyTrafficData_CMockReturnMemThruPtr_out(UNITY_LINE_TYPE cmock_line, LEDData const* out, size_t cmock_size)
{
  CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_copyTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.copyTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_out_Used = 1;
  cmock_call_instance->ReturnThruPtr_out_Val = out;
  cmock_call_instance->ReturnThruPtr_out_Size = cmock_size;
}

void copyTrafficData_CMockIgnoreArg_out(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_copyTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.copyTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_out = 1;
}

void copyTrafficData_CMockIgnoreArg_outLen(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_copyTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.copyTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_outLen = 1;
}

void copyTrafficData_CMockIgnoreArg_dir(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_copyTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.copyTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dir = 1;
}

void copyTrafficData_CMockIgnoreArg_category(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_copyTrafficData_CALL_INSTANCE* cmock_call_instance = (CMOCK_copyTrafficData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.copyTrafficData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_category = 1;
}

