/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockapi_connect.h"

static const char* CMockString_URL = "URL";
static const char* CMockString_client = "client";
static const char* CMockString_contentLength = "contentLength";
static const char* CMockString_getServerSpeeds = "getServerSpeeds";
static const char* CMockString_ledSpeeds = "ledSpeeds";
static const char* CMockString_ledSpeedsLen = "ledSpeedsLen";
static const char* CMockString_openServerFile = "openServerFile";
static const char* CMockString_retryNum = "retryNum";

typedef struct _CMOCK_openServerFile_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int64_t* Expected_contentLength;
  esp_http_client_handle_t Expected_client;
  const char* Expected_URL;
  int Expected_retryNum;

} CMOCK_openServerFile_CALL_INSTANCE;

typedef struct _CMOCK_getServerSpeeds_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  LEDData* Expected_ledSpeeds;
  uint32_t Expected_ledSpeedsLen;
  esp_http_client_handle_t Expected_client;
  char* Expected_URL;
  int Expected_retryNum;

} CMOCK_getServerSpeeds_CALL_INSTANCE;

static struct Mockapi_connectInstance
{
  char openServerFile_IgnoreBool;
  esp_err_t openServerFile_FinalReturn;
  CMOCK_MEM_INDEX_TYPE openServerFile_CallInstance;
  char getServerSpeeds_IgnoreBool;
  esp_err_t getServerSpeeds_FinalReturn;
  CMOCK_MEM_INDEX_TYPE getServerSpeeds_CallInstance;
} Mock;


void Mockapi_connect_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.openServerFile_CallInstance;
  if (Mock.openServerFile_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_openServerFile);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.getServerSpeeds_CallInstance;
  if (Mock.getServerSpeeds_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_getServerSpeeds);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockapi_connect_Init(void)
{
  Mockapi_connect_Destroy();
}

void Mockapi_connect_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

esp_err_t openServerFile(int64_t* contentLength, esp_http_client_handle_t client, const char* URL, int retryNum)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_openServerFile_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_openServerFile);
  cmock_call_instance = (CMOCK_openServerFile_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.openServerFile_CallInstance);
  Mock.openServerFile_CallInstance = CMock_Guts_MemNext(Mock.openServerFile_CallInstance);
  if (Mock.openServerFile_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.openServerFile_FinalReturn;
    memcpy((void*)(&Mock.openServerFile_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_openServerFile,CMockString_contentLength);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_contentLength), (void*)(contentLength), sizeof(int64_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_openServerFile,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_openServerFile,CMockString_URL);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_URL, URL, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_openServerFile,CMockString_retryNum);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_retryNum, retryNum, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_openServerFile(CMOCK_openServerFile_CALL_INSTANCE* cmock_call_instance, int64_t* contentLength, esp_http_client_handle_t client, const char* URL, int retryNum);
void CMockExpectParameters_openServerFile(CMOCK_openServerFile_CALL_INSTANCE* cmock_call_instance, int64_t* contentLength, esp_http_client_handle_t client, const char* URL, int retryNum)
{
  cmock_call_instance->Expected_contentLength = contentLength;
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_URL = URL;
  cmock_call_instance->Expected_retryNum = retryNum;
}

void openServerFile_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_openServerFile_CALL_INSTANCE));
  CMOCK_openServerFile_CALL_INSTANCE* cmock_call_instance = (CMOCK_openServerFile_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.openServerFile_CallInstance = CMock_Guts_MemChain(Mock.openServerFile_CallInstance, cmock_guts_index);
  Mock.openServerFile_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.openServerFile_IgnoreBool = (char)1;
}

void openServerFile_CMockStopIgnore(void)
{
  if(Mock.openServerFile_IgnoreBool)
    Mock.openServerFile_CallInstance = CMock_Guts_MemNext(Mock.openServerFile_CallInstance);
  Mock.openServerFile_IgnoreBool = (char)0;
}

void openServerFile_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int64_t* contentLength, esp_http_client_handle_t client, const char* URL, int retryNum, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_openServerFile_CALL_INSTANCE));
  CMOCK_openServerFile_CALL_INSTANCE* cmock_call_instance = (CMOCK_openServerFile_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.openServerFile_CallInstance = CMock_Guts_MemChain(Mock.openServerFile_CallInstance, cmock_guts_index);
  Mock.openServerFile_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_openServerFile(cmock_call_instance, contentLength, client, URL, retryNum);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

esp_err_t getServerSpeeds(LEDData* ledSpeeds, uint32_t ledSpeedsLen, esp_http_client_handle_t client, char* URL, int retryNum)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_getServerSpeeds_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_getServerSpeeds);
  cmock_call_instance = (CMOCK_getServerSpeeds_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.getServerSpeeds_CallInstance);
  Mock.getServerSpeeds_CallInstance = CMock_Guts_MemNext(Mock.getServerSpeeds_CallInstance);
  if (Mock.getServerSpeeds_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.getServerSpeeds_FinalReturn;
    memcpy((void*)(&Mock.getServerSpeeds_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_getServerSpeeds,CMockString_ledSpeeds);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ledSpeeds), (void*)(ledSpeeds), sizeof(LEDData), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_getServerSpeeds,CMockString_ledSpeedsLen);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ledSpeedsLen, ledSpeedsLen, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_getServerSpeeds,CMockString_client);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_client), (void*)(&client), sizeof(esp_http_client_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_getServerSpeeds,CMockString_URL);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_URL, URL, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_getServerSpeeds,CMockString_retryNum);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_retryNum, retryNum, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_getServerSpeeds(CMOCK_getServerSpeeds_CALL_INSTANCE* cmock_call_instance, LEDData* ledSpeeds, uint32_t ledSpeedsLen, esp_http_client_handle_t client, char* URL, int retryNum);
void CMockExpectParameters_getServerSpeeds(CMOCK_getServerSpeeds_CALL_INSTANCE* cmock_call_instance, LEDData* ledSpeeds, uint32_t ledSpeedsLen, esp_http_client_handle_t client, char* URL, int retryNum)
{
  cmock_call_instance->Expected_ledSpeeds = ledSpeeds;
  cmock_call_instance->Expected_ledSpeedsLen = ledSpeedsLen;
  memcpy((void*)(&cmock_call_instance->Expected_client), (const void*)(&client),
         sizeof(esp_http_client_handle_t[sizeof(client) == sizeof(esp_http_client_handle_t) ? 1 : -1])); /* add esp_http_client_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_URL = URL;
  cmock_call_instance->Expected_retryNum = retryNum;
}

void getServerSpeeds_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getServerSpeeds_CALL_INSTANCE));
  CMOCK_getServerSpeeds_CALL_INSTANCE* cmock_call_instance = (CMOCK_getServerSpeeds_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getServerSpeeds_CallInstance = CMock_Guts_MemChain(Mock.getServerSpeeds_CallInstance, cmock_guts_index);
  Mock.getServerSpeeds_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.getServerSpeeds_IgnoreBool = (char)1;
}

void getServerSpeeds_CMockStopIgnore(void)
{
  if(Mock.getServerSpeeds_IgnoreBool)
    Mock.getServerSpeeds_CallInstance = CMock_Guts_MemNext(Mock.getServerSpeeds_CallInstance);
  Mock.getServerSpeeds_IgnoreBool = (char)0;
}

void getServerSpeeds_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, LEDData* ledSpeeds, uint32_t ledSpeedsLen, esp_http_client_handle_t client, char* URL, int retryNum, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getServerSpeeds_CALL_INSTANCE));
  CMOCK_getServerSpeeds_CALL_INSTANCE* cmock_call_instance = (CMOCK_getServerSpeeds_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getServerSpeeds_CallInstance = CMock_Guts_MemChain(Mock.getServerSpeeds_CallInstance, cmock_guts_index);
  Mock.getServerSpeeds_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_getServerSpeeds(cmock_call_instance, ledSpeeds, ledSpeedsLen, client, URL, retryNum);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

