/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockota.h"

#include "esp_log.h"

static const char* CMockString_available = "available";
static const char* CMockString_createOTATask = "createOTATask";
static const char* CMockString_getOTATask = "getOTATask";
static const char* CMockString_handle = "handle";
static const char* CMockString_patch = "patch";
static const char* CMockString_queryOTAUpdateAvailable = "queryOTAUpdateAvailable";

typedef struct _CMOCK_getOTATask_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  TaskHandle_t ReturnVal;

} CMOCK_getOTATask_CALL_INSTANCE;

typedef struct _CMOCK_createOTATask_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  TaskHandle_t* Expected_handle;
  char ReturnThruPtr_handle_Used;
  TaskHandle_t const* ReturnThruPtr_handle_Val;
  size_t ReturnThruPtr_handle_Size;
  char IgnoreArg_handle;

} CMOCK_createOTATask_CALL_INSTANCE;

typedef struct _CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  bool* Expected_available;
  bool* Expected_patch;
  char ReturnThruPtr_available_Used;
  bool const* ReturnThruPtr_available_Val;
  size_t ReturnThruPtr_available_Size;
  char ReturnThruPtr_patch_Used;
  bool const* ReturnThruPtr_patch_Val;
  size_t ReturnThruPtr_patch_Size;
  char IgnoreArg_available;
  char IgnoreArg_patch;

} CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE;

static struct MockotaInstance
{
  char getOTATask_IgnoreBool;
  TaskHandle_t getOTATask_FinalReturn;
  char getOTATask_CallbackBool;
  CMOCK_getOTATask_CALLBACK getOTATask_CallbackFunctionPointer;
  int getOTATask_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE getOTATask_CallInstance;
  char createOTATask_IgnoreBool;
  esp_err_t createOTATask_FinalReturn;
  char createOTATask_CallbackBool;
  CMOCK_createOTATask_CALLBACK createOTATask_CallbackFunctionPointer;
  int createOTATask_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE createOTATask_CallInstance;
  char queryOTAUpdateAvailable_IgnoreBool;
  esp_err_t queryOTAUpdateAvailable_FinalReturn;
  char queryOTAUpdateAvailable_CallbackBool;
  CMOCK_queryOTAUpdateAvailable_CALLBACK queryOTAUpdateAvailable_CallbackFunctionPointer;
  int queryOTAUpdateAvailable_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE queryOTAUpdateAvailable_CallInstance;
} Mock;


void Mockota_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.getOTATask_CallInstance;
  if (Mock.getOTATask_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_getOTATask);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.getOTATask_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.createOTATask_CallInstance;
  if (Mock.createOTATask_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_createOTATask);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.createOTATask_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.queryOTAUpdateAvailable_CallInstance;
  if (Mock.queryOTAUpdateAvailable_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_queryOTAUpdateAvailable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.queryOTAUpdateAvailable_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockota_Init(void)
{
  Mockota_Destroy();
}

void Mockota_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

TaskHandle_t getOTATask(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_getOTATask_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_getOTATask);
  cmock_call_instance = (CMOCK_getOTATask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.getOTATask_CallInstance);
  Mock.getOTATask_CallInstance = CMock_Guts_MemNext(Mock.getOTATask_CallInstance);
  if (Mock.getOTATask_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.getOTATask_FinalReturn;
    memcpy((void*)(&Mock.getOTATask_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(TaskHandle_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(TaskHandle_t) ? 1 : -1])); /* add TaskHandle_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.getOTATask_CallbackBool &&
      Mock.getOTATask_CallbackFunctionPointer != NULL)
  {
    TaskHandle_t cmock_cb_ret = Mock.getOTATask_CallbackFunctionPointer(Mock.getOTATask_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.getOTATask_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.getOTATask_CallbackFunctionPointer(Mock.getOTATask_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void getOTATask_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, TaskHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getOTATask_CALL_INSTANCE));
  CMOCK_getOTATask_CALL_INSTANCE* cmock_call_instance = (CMOCK_getOTATask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getOTATask_CallInstance = CMock_Guts_MemChain(Mock.getOTATask_CallInstance, cmock_guts_index);
  Mock.getOTATask_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.getOTATask_IgnoreBool = (char)1;
}

void getOTATask_CMockStopIgnore(void)
{
  if(Mock.getOTATask_IgnoreBool)
    Mock.getOTATask_CallInstance = CMock_Guts_MemNext(Mock.getOTATask_CallInstance);
  Mock.getOTATask_IgnoreBool = (char)0;
}

void getOTATask_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TaskHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getOTATask_CALL_INSTANCE));
  CMOCK_getOTATask_CALL_INSTANCE* cmock_call_instance = (CMOCK_getOTATask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getOTATask_CallInstance = CMock_Guts_MemChain(Mock.getOTATask_CallInstance, cmock_guts_index);
  Mock.getOTATask_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(TaskHandle_t[sizeof(cmock_to_return) == sizeof(TaskHandle_t) ? 1 : -1])); /* add TaskHandle_t to :treat_as_array if this causes an error */
}

void getOTATask_AddCallback(CMOCK_getOTATask_CALLBACK Callback)
{
  Mock.getOTATask_IgnoreBool = (char)0;
  Mock.getOTATask_CallbackBool = (char)1;
  Mock.getOTATask_CallbackFunctionPointer = Callback;
}

void getOTATask_Stub(CMOCK_getOTATask_CALLBACK Callback)
{
  Mock.getOTATask_IgnoreBool = (char)0;
  Mock.getOTATask_CallbackBool = (char)0;
  Mock.getOTATask_CallbackFunctionPointer = Callback;
}

esp_err_t createOTATask(TaskHandle_t* handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_createOTATask_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_createOTATask);
  cmock_call_instance = (CMOCK_createOTATask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.createOTATask_CallInstance);
  Mock.createOTATask_CallInstance = CMock_Guts_MemNext(Mock.createOTATask_CallInstance);
  if (Mock.createOTATask_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.createOTATask_FinalReturn;
    memcpy((void*)(&Mock.createOTATask_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.createOTATask_CallbackBool &&
      Mock.createOTATask_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.createOTATask_CallbackFunctionPointer(handle, Mock.createOTATask_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_handle)
  {
    UNITY_SET_DETAILS(CMockString_createOTATask,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_handle), (void*)(handle), sizeof(TaskHandle_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.createOTATask_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.createOTATask_CallbackFunctionPointer(handle, Mock.createOTATask_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_handle_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(handle, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)handle, (const void*)cmock_call_instance->ReturnThruPtr_handle_Val,
      cmock_call_instance->ReturnThruPtr_handle_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_createOTATask(CMOCK_createOTATask_CALL_INSTANCE* cmock_call_instance, TaskHandle_t* handle);
void CMockExpectParameters_createOTATask(CMOCK_createOTATask_CALL_INSTANCE* cmock_call_instance, TaskHandle_t* handle)
{
  cmock_call_instance->Expected_handle = handle;
  cmock_call_instance->IgnoreArg_handle = 0;
  cmock_call_instance->ReturnThruPtr_handle_Used = 0;
}

void createOTATask_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_createOTATask_CALL_INSTANCE));
  CMOCK_createOTATask_CALL_INSTANCE* cmock_call_instance = (CMOCK_createOTATask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.createOTATask_CallInstance = CMock_Guts_MemChain(Mock.createOTATask_CallInstance, cmock_guts_index);
  Mock.createOTATask_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.createOTATask_IgnoreBool = (char)1;
}

void createOTATask_CMockStopIgnore(void)
{
  if(Mock.createOTATask_IgnoreBool)
    Mock.createOTATask_CallInstance = CMock_Guts_MemNext(Mock.createOTATask_CallInstance);
  Mock.createOTATask_IgnoreBool = (char)0;
}

void createOTATask_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TaskHandle_t* handle, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_createOTATask_CALL_INSTANCE));
  CMOCK_createOTATask_CALL_INSTANCE* cmock_call_instance = (CMOCK_createOTATask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.createOTATask_CallInstance = CMock_Guts_MemChain(Mock.createOTATask_CallInstance, cmock_guts_index);
  Mock.createOTATask_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_createOTATask(cmock_call_instance, handle);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void createOTATask_AddCallback(CMOCK_createOTATask_CALLBACK Callback)
{
  Mock.createOTATask_IgnoreBool = (char)0;
  Mock.createOTATask_CallbackBool = (char)1;
  Mock.createOTATask_CallbackFunctionPointer = Callback;
}

void createOTATask_Stub(CMOCK_createOTATask_CALLBACK Callback)
{
  Mock.createOTATask_IgnoreBool = (char)0;
  Mock.createOTATask_CallbackBool = (char)0;
  Mock.createOTATask_CallbackFunctionPointer = Callback;
}

void createOTATask_CMockReturnMemThruPtr_handle(UNITY_LINE_TYPE cmock_line, TaskHandle_t const* handle, size_t cmock_size)
{
  CMOCK_createOTATask_CALL_INSTANCE* cmock_call_instance = (CMOCK_createOTATask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.createOTATask_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_handle_Used = 1;
  cmock_call_instance->ReturnThruPtr_handle_Val = handle;
  cmock_call_instance->ReturnThruPtr_handle_Size = cmock_size;
}

void createOTATask_CMockIgnoreArg_handle(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_createOTATask_CALL_INSTANCE* cmock_call_instance = (CMOCK_createOTATask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.createOTATask_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_handle = 1;
}

esp_err_t queryOTAUpdateAvailable(bool* available, bool* patch)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_queryOTAUpdateAvailable);
  cmock_call_instance = (CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.queryOTAUpdateAvailable_CallInstance);
  Mock.queryOTAUpdateAvailable_CallInstance = CMock_Guts_MemNext(Mock.queryOTAUpdateAvailable_CallInstance);
  if (Mock.queryOTAUpdateAvailable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.queryOTAUpdateAvailable_FinalReturn;
    memcpy((void*)(&Mock.queryOTAUpdateAvailable_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.queryOTAUpdateAvailable_CallbackBool &&
      Mock.queryOTAUpdateAvailable_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.queryOTAUpdateAvailable_CallbackFunctionPointer(available, patch, Mock.queryOTAUpdateAvailable_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_available)
  {
    UNITY_SET_DETAILS(CMockString_queryOTAUpdateAvailable,CMockString_available);
    if (cmock_call_instance->Expected_available == NULL)
      { UNITY_TEST_ASSERT_NULL(available, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_available, available, 1, cmock_line, CMockStringMismatch); }
  }
  ESP_LOGI("mock", "ignorearg: %d", cmock_call_instance->IgnoreArg_patch);
  if (!cmock_call_instance->IgnoreArg_patch)
  {
    UNITY_SET_DETAILS(CMockString_queryOTAUpdateAvailable,CMockString_patch);
    if (cmock_call_instance->Expected_patch == NULL)
      { UNITY_TEST_ASSERT_NULL(patch, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_patch, patch, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.queryOTAUpdateAvailable_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.queryOTAUpdateAvailable_CallbackFunctionPointer(available, patch, Mock.queryOTAUpdateAvailable_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_available_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(available, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)available, (const void*)cmock_call_instance->ReturnThruPtr_available_Val,
      cmock_call_instance->ReturnThruPtr_available_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_patch_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(patch, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)patch, (const void*)cmock_call_instance->ReturnThruPtr_patch_Val,
      cmock_call_instance->ReturnThruPtr_patch_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_queryOTAUpdateAvailable(CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE* cmock_call_instance, bool* available, bool* patch);
void CMockExpectParameters_queryOTAUpdateAvailable(CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE* cmock_call_instance, bool* available, bool* patch)
{
  cmock_call_instance->Expected_available = available;
  cmock_call_instance->IgnoreArg_available = 0;
  cmock_call_instance->ReturnThruPtr_available_Used = 0;
  cmock_call_instance->Expected_patch = patch;
  cmock_call_instance->IgnoreArg_patch = 0;
  cmock_call_instance->ReturnThruPtr_patch_Used = 0;
}

void queryOTAUpdateAvailable_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE));
  CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.queryOTAUpdateAvailable_CallInstance = CMock_Guts_MemChain(Mock.queryOTAUpdateAvailable_CallInstance, cmock_guts_index);
  Mock.queryOTAUpdateAvailable_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.queryOTAUpdateAvailable_IgnoreBool = (char)1;
}

void queryOTAUpdateAvailable_CMockStopIgnore(void)
{
  if(Mock.queryOTAUpdateAvailable_IgnoreBool)
    Mock.queryOTAUpdateAvailable_CallInstance = CMock_Guts_MemNext(Mock.queryOTAUpdateAvailable_CallInstance);
  Mock.queryOTAUpdateAvailable_IgnoreBool = (char)0;
}

void queryOTAUpdateAvailable_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool* available, bool* patch, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE));
  CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.queryOTAUpdateAvailable_CallInstance = CMock_Guts_MemChain(Mock.queryOTAUpdateAvailable_CallInstance, cmock_guts_index);
  Mock.queryOTAUpdateAvailable_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_queryOTAUpdateAvailable(cmock_call_instance, available, patch);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void queryOTAUpdateAvailable_AddCallback(CMOCK_queryOTAUpdateAvailable_CALLBACK Callback)
{
  Mock.queryOTAUpdateAvailable_IgnoreBool = (char)0;
  Mock.queryOTAUpdateAvailable_CallbackBool = (char)1;
  Mock.queryOTAUpdateAvailable_CallbackFunctionPointer = Callback;
}

void queryOTAUpdateAvailable_Stub(CMOCK_queryOTAUpdateAvailable_CALLBACK Callback)
{
  Mock.queryOTAUpdateAvailable_IgnoreBool = (char)0;
  Mock.queryOTAUpdateAvailable_CallbackBool = (char)0;
  Mock.queryOTAUpdateAvailable_CallbackFunctionPointer = Callback;
}

void queryOTAUpdateAvailable_CMockReturnMemThruPtr_available(UNITY_LINE_TYPE cmock_line, bool const* available, size_t cmock_size)
{
  CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.queryOTAUpdateAvailable_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_available_Used = 1;
  cmock_call_instance->ReturnThruPtr_available_Val = available;
  cmock_call_instance->ReturnThruPtr_available_Size = cmock_size;
}

void queryOTAUpdateAvailable_CMockReturnMemThruPtr_patch(UNITY_LINE_TYPE cmock_line, bool const* patch, size_t cmock_size)
{
  CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.queryOTAUpdateAvailable_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_patch_Used = 1;
  cmock_call_instance->ReturnThruPtr_patch_Val = patch;
  cmock_call_instance->ReturnThruPtr_patch_Size = cmock_size;
}

void queryOTAUpdateAvailable_CMockIgnoreArg_available(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.queryOTAUpdateAvailable_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_available = 1;
}

void queryOTAUpdateAvailable_CMockIgnoreArg_patch(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_queryOTAUpdateAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.queryOTAUpdateAvailable_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_patch = 1;
}

